import { Question } from './types';

export const personalityQuestions: Question[] = [
  // ============ MANDATORY QUESTIONS (1-20) ============
  
  // Big Five - Openness (1-4)
  {
    id: 'q1',
    category: 'personality',
    text: 'I enjoy trying new experiences and exploring unfamiliar places.',
    trait: 'openness',
    type: 'scale',
    isMandatory: true,
    weight: 1.5,
  },
  {
    id: 'q2',
    category: 'personality',
    text: 'I am fascinated by art, music, and creative expressions.',
    trait: 'openness',
    type: 'scale',
    isMandatory: true,
    weight: 1,
  },
  {
    id: 'q3',
    category: 'personality',
    text: 'I prefer familiar routines over spontaneous changes.',
    trait: 'openness',
    type: 'scale',
    isMandatory: true,
    weight: -1, // Reverse scored
  },
  {
    id: 'q4',
    category: 'personality',
    text: 'I often think about abstract concepts and philosophical questions.',
    trait: 'openness',
    type: 'scale',
    isMandatory: true,
    weight: 1,
  },

  // Big Five - Conscientiousness (5-8)
  {
    id: 'q5',
    category: 'personality',
    text: 'I keep my living and working spaces organized.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: true,
    weight: 1.5,
  },
  {
    id: 'q6',
    category: 'personality',
    text: 'I always finish what I start, even when it gets difficult.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: true,
    weight: 1,
  },
  {
    id: 'q7',
    category: 'personality',
    text: 'I often procrastinate on important tasks.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: true,
    weight: -1,
  },
  {
    id: 'q8',
    category: 'personality',
    text: 'I carefully plan before making decisions.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: true,
    weight: 1,
  },

  // Big Five - Extraversion (9-12)
  {
    id: 'q9',
    category: 'social',
    text: 'I feel energized after spending time with groups of people.',
    trait: 'extraversion',
    type: 'scale',
    isMandatory: true,
    weight: 1.5,
  },
  {
    id: 'q10',
    category: 'social',
    text: 'I prefer quiet evenings at home over parties.',
    trait: 'extraversion',
    type: 'scale',
    isMandatory: true,
    weight: -1,
  },
  {
    id: 'q11',
    category: 'social',
    text: 'I am usually the one who initiates conversations with strangers.',
    trait: 'extraversion',
    type: 'scale',
    isMandatory: true,
    weight: 1,
  },
  {
    id: 'q12',
    category: 'social',
    text: 'I need alone time to recharge after social events.',
    trait: 'extraversion',
    type: 'scale',
    isMandatory: true,
    weight: -1,
  },

  // Big Five - Agreeableness (13-16)
  {
    id: 'q13',
    category: 'emotional',
    text: 'I genuinely care about other people\'s problems and try to help.',
    trait: 'agreeableness',
    type: 'scale',
    isMandatory: true,
    weight: 1.5,
  },
  {
    id: 'q14',
    category: 'emotional',
    text: 'I find it easy to forgive people who have wronged me.',
    trait: 'agreeableness',
    type: 'scale',
    isMandatory: true,
    weight: 1,
  },
  {
    id: 'q15',
    category: 'emotional',
    text: 'I tend to be skeptical of others\' intentions.',
    trait: 'agreeableness',
    type: 'scale',
    isMandatory: true,
    weight: -1,
  },
  {
    id: 'q16',
    category: 'emotional',
    text: 'I prioritize cooperation over competition in most situations.',
    trait: 'agreeableness',
    type: 'scale',
    isMandatory: true,
    weight: 1,
  },

  // Big Five - Neuroticism (17-20)
  {
    id: 'q17',
    category: 'emotional',
    text: 'I often feel anxious or worried about things.',
    trait: 'neuroticism',
    type: 'scale',
    isMandatory: true,
    weight: 1.5,
  },
  {
    id: 'q18',
    category: 'emotional',
    text: 'I recover quickly from setbacks and disappointments.',
    trait: 'neuroticism',
    type: 'scale',
    isMandatory: true,
    weight: -1,
  },
  {
    id: 'q19',
    category: 'emotional',
    text: 'My mood can change significantly throughout the day.',
    trait: 'neuroticism',
    type: 'scale',
    isMandatory: true,
    weight: 1,
  },
  {
    id: 'q20',
    category: 'emotional',
    text: 'I generally feel secure and confident in who I am.',
    trait: 'neuroticism',
    type: 'scale',
    isMandatory: true,
    weight: -1,
  },

  // ============ OPTIONAL QUESTIONS (21-100) ============

  // Emotional Intelligence (21-30)
  {
    id: 'q21',
    category: 'emotional',
    text: 'I can accurately identify what emotions I am feeling.',
    trait: 'emotionalIntelligence',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q22',
    category: 'emotional',
    text: 'I can tell how others are feeling just by looking at them.',
    trait: 'emotionalIntelligence',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q23',
    category: 'emotional',
    text: 'I manage my emotions well, even in stressful situations.',
    trait: 'emotionalIntelligence',
    type: 'scale',
    isMandatory: false,
    weight: 1.2,
  },
  {
    id: 'q24',
    category: 'emotional',
    text: 'When someone shares their problems, I truly feel their pain.',
    trait: 'empathy',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q25',
    category: 'emotional',
    text: 'I cry easily when watching emotional movies or hearing sad stories.',
    textMale: 'I feel emotionally moved when watching emotional movies or hearing sad stories.',
    textFemale: 'I cry easily when watching emotional movies or hearing sad stories.',
    trait: 'empathy',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q26',
    category: 'emotional',
    text: 'I can separate my emotions from my decisions when needed.',
    trait: 'emotionalIntelligence',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q27',
    category: 'emotional',
    text: 'After a major disappointment, I can pick myself up within a few days.',
    trait: 'resilience',
    type: 'scale',
    isMandatory: false,
    weight: 1.2,
  },
  {
    id: 'q28',
    category: 'emotional',
    text: 'I believe that challenges make me stronger.',
    trait: 'resilience',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q29',
    category: 'emotional',
    text: 'I tend to dwell on past mistakes and regrets.',
    trait: 'resilience',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },
  {
    id: 'q30',
    category: 'emotional',
    text: 'I express my feelings openly with people I trust.',
    trait: 'emotionalIntelligence',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },

  // Communication Style (31-40)
  {
    id: 'q31',
    category: 'communication',
    text: 'I prefer direct, straightforward communication over hints.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q32',
    category: 'communication',
    text: 'I am comfortable expressing my needs and boundaries clearly.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: 1.2,
  },
  {
    id: 'q33',
    category: 'communication',
    text: 'I listen more than I speak in conversations.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q34',
    category: 'communication',
    text: 'I feel comfortable discussing deep personal topics.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q35',
    category: 'communication',
    text: 'I often use humor to defuse tense situations.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: 0.8,
  },
  {
    id: 'q36',
    category: 'communication',
    text: 'I prefer texting over phone calls.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: 0.5,
  },
  {
    id: 'q37',
    category: 'communication',
    text: 'I find it easy to apologize when I am wrong.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: 1.2,
  },
  {
    id: 'q38',
    category: 'communication',
    text: 'I need time to process before responding to important matters.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: 0.8,
  },
  {
    id: 'q39',
    category: 'communication',
    text: 'I often say things without thinking them through first.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: -0.8,
  },
  {
    id: 'q40',
    category: 'communication',
    text: 'I validate others\' feelings even when I disagree with them.',
    trait: 'empathy',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },

  // Conflict Resolution (41-50)
  {
    id: 'q41',
    category: 'conflict',
    text: 'When angry, I need space before discussing the issue.',
    trait: 'conflictResolution',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q42',
    category: 'conflict',
    text: 'I prefer to resolve conflicts immediately rather than let them linger.',
    trait: 'conflictResolution',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q43',
    category: 'conflict',
    text: 'During arguments, I focus on finding solutions rather than winning.',
    trait: 'conflictResolution',
    type: 'scale',
    isMandatory: false,
    weight: 1.5,
  },
  {
    id: 'q44',
    category: 'conflict',
    text: 'I sometimes give the silent treatment when upset.',
    trait: 'conflictResolution',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },
  {
    id: 'q45',
    category: 'conflict',
    text: 'I am willing to compromise even on things important to me.',
    trait: 'conflictResolution',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q46',
    category: 'conflict',
    text: 'I avoid conflict even when issues need to be addressed.',
    trait: 'conflictResolution',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },
  {
    id: 'q47',
    category: 'conflict',
    text: 'I can stay calm and rational during heated discussions.',
    trait: 'conflictResolution',
    type: 'scale',
    isMandatory: false,
    weight: 1.2,
  },
  {
    id: 'q48',
    category: 'conflict',
    text: 'I hold grudges even after conflicts are resolved.',
    trait: 'conflictResolution',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },
  {
    id: 'q49',
    category: 'conflict',
    text: 'I take responsibility for my part in relationship problems.',
    trait: 'conflictResolution',
    type: 'scale',
    isMandatory: false,
    weight: 1.5,
  },
  {
    id: 'q50',
    category: 'conflict',
    text: 'I become defensive when receiving criticism.',
    trait: 'conflictResolution',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },

  // Relationship & Attachment (51-60)
  {
    id: 'q51',
    category: 'relationship',
    text: 'I feel comfortable being emotionally dependent on a partner.',
    trait: 'attachment',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q52',
    category: 'relationship',
    text: 'I worry about my partner losing interest in me.',
    trait: 'attachment',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q53',
    category: 'relationship',
    text: 'I need a lot of reassurance in relationships.',
    trait: 'attachment',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q54',
    category: 'relationship',
    text: 'I prefer maintaining some independence even in close relationships.',
    trait: 'attachment',
    type: 'scale',
    isMandatory: false,
    weight: -0.5,
  },
  {
    id: 'q55',
    category: 'relationship',
    text: 'I find it easy to trust romantic partners.',
    trait: 'attachment',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q56',
    category: 'relationship',
    textMale: 'I believe a man should be the primary provider in a relationship.',
    textFemale: 'I believe in traditional gender roles in relationships.',
    text: 'I believe in traditional gender roles in relationships.',
    trait: 'traditionalism',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q57',
    category: 'relationship',
    text: 'I believe in equal sharing of household responsibilities.',
    trait: 'traditionalism',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },
  {
    id: 'q58',
    category: 'relationship',
    text: 'Physical affection is very important to me in a relationship.',
    trait: 'loveLanguage',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q59',
    category: 'relationship',
    text: 'I feel most loved when my partner spends quality time with me.',
    trait: 'loveLanguage',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q60',
    category: 'relationship',
    text: 'Words of affirmation mean more to me than gifts or actions.',
    trait: 'loveLanguage',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },

  // Intimacy & Physical (61-70)
  {
    id: 'q61',
    category: 'intimacy',
    text: 'Physical intimacy is a priority for me in romantic relationships.',
    trait: 'attachment',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q62',
    category: 'intimacy',
    text: 'I am comfortable discussing intimate preferences with my partner.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: 1.2,
  },
  {
    id: 'q63',
    category: 'intimacy',
    text: 'Emotional connection must precede physical intimacy for me.',
    trait: 'attachment',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q64',
    category: 'intimacy',
    textMale: 'I am comfortable being vulnerable and showing my emotions.',
    textFemale: 'I appreciate when my partner is emotionally vulnerable with me.',
    text: 'I am comfortable being vulnerable and showing my emotions.',
    trait: 'emotionalIntelligence',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q65',
    category: 'intimacy',
    text: 'I enjoy giving and receiving physical affection throughout the day.',
    trait: 'loveLanguage',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q66',
    category: 'intimacy',
    text: 'I believe in waiting until marriage for physical intimacy.',
    trait: 'traditionalism',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q67',
    category: 'intimacy',
    text: 'I am comfortable with public displays of affection.',
    trait: 'extraversion',
    type: 'scale',
    isMandatory: false,
    weight: 0.5,
  },
  {
    id: 'q68',
    category: 'intimacy',
    text: 'I feel connected to my partner through shared experiences.',
    trait: 'attachment',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q69',
    category: 'intimacy',
    text: 'I can distinguish between physical attraction and emotional connection.',
    trait: 'emotionalIntelligence',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q70',
    category: 'intimacy',
    text: 'I believe intimacy grows stronger with trust and time.',
    trait: 'attachment',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },

  // Lifestyle & Social (71-80)
  {
    id: 'q71',
    category: 'lifestyle',
    text: 'I enjoy meeting new people and expanding my social circle.',
    trait: 'socialEnergy',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q72',
    category: 'lifestyle',
    text: 'I prefer spending weekends at home rather than going out.',
    trait: 'socialEnergy',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },
  {
    id: 'q73',
    category: 'lifestyle',
    text: 'Adventure and travel are essential parts of my life.',
    trait: 'adventurousness',
    type: 'scale',
    isMandatory: false,
    weight: 1.2,
  },
  {
    id: 'q74',
    category: 'lifestyle',
    text: 'I prefer stability and routine over spontaneity.',
    trait: 'adventurousness',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },
  {
    id: 'q75',
    category: 'lifestyle',
    text: 'Fitness and physical health are priorities for me.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: false,
    weight: 0.8,
  },
  {
    id: 'q76',
    category: 'lifestyle',
    text: 'I am a morning person who wakes up early naturally.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: false,
    weight: 0.5,
  },
  {
    id: 'q77',
    category: 'lifestyle',
    text: 'I enjoy cooking and preparing meals at home.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: false,
    weight: 0.5,
  },
  {
    id: 'q78',
    category: 'lifestyle',
    text: 'I spend more time on personal hobbies than social activities.',
    trait: 'socialEnergy',
    type: 'scale',
    isMandatory: false,
    weight: -0.8,
  },
  {
    id: 'q79',
    category: 'lifestyle',
    text: 'I am ambitious about my career and professional growth.',
    trait: 'careerDrive',
    type: 'scale',
    isMandatory: false,
    weight: 1.2,
  },
  {
    id: 'q80',
    category: 'lifestyle',
    text: 'Work-life balance is more important to me than career success.',
    trait: 'careerDrive',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },

  // Family & Future (81-90)
  {
    id: 'q81',
    category: 'future',
    text: 'Having children is very important to me.',
    trait: 'familyOrientation',
    type: 'scale',
    isMandatory: false,
    weight: 1.5,
  },
  {
    id: 'q82',
    category: 'future',
    text: 'Family gatherings and traditions are meaningful to me.',
    trait: 'familyOrientation',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q83',
    category: 'future',
    text: 'I want to live close to my extended family.',
    trait: 'familyOrientation',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q84',
    category: 'future',
    text: 'Financial security is my top priority for the future.',
    trait: 'careerDrive',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q85',
    category: 'future',
    text: 'I prefer city life over rural or suburban living.',
    trait: 'socialEnergy',
    type: 'scale',
    isMandatory: false,
    weight: 0.5,
  },
  {
    id: 'q86',
    category: 'future',
    text: 'I am open to relocating for the right opportunity.',
    trait: 'adventurousness',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q87',
    category: 'future',
    text: 'I believe in saving money rather than spending on experiences.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: false,
    weight: 0.5,
  },
  {
    id: 'q88',
    category: 'future',
    textMale: 'I want a partner who prioritizes family over career.',
    textFemale: 'I want to prioritize family once I have children.',
    text: 'I believe family should come before career.',
    trait: 'familyOrientation',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q89',
    category: 'future',
    text: 'I have a clear vision for where I want to be in 10 years.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q90',
    category: 'future',
    text: 'I prefer to take life as it comes rather than plan ahead.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },

  // Values & Spirituality (91-100)
  {
    id: 'q91',
    category: 'values',
    text: 'Spirituality or religion plays an important role in my life.',
    trait: 'spirituality',
    type: 'scale',
    isMandatory: false,
    weight: 1.5,
  },
  {
    id: 'q92',
    category: 'values',
    text: 'I practice meditation, prayer, or other spiritual activities.',
    trait: 'spirituality',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q93',
    category: 'values',
    text: 'I believe in respecting traditional values and customs.',
    trait: 'traditionalism',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q94',
    category: 'values',
    text: 'I am open to changing my beliefs based on new information.',
    trait: 'intellectualism',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q95',
    category: 'values',
    text: 'Honesty is more important than sparing someone\'s feelings.',
    trait: 'communicationStyle',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q96',
    category: 'values',
    text: 'I enjoy intellectual discussions and debates.',
    trait: 'intellectualism',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q97',
    category: 'values',
    text: 'I believe in giving back to the community and helping others.',
    trait: 'agreeableness',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q98',
    category: 'values',
    text: 'Personal freedom is more important than social expectations.',
    trait: 'traditionalism',
    type: 'scale',
    isMandatory: false,
    weight: -1,
  },
  {
    id: 'q99',
    category: 'values',
    text: 'I believe in finding meaning and purpose in my work.',
    trait: 'careerDrive',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
  {
    id: 'q100',
    category: 'values',
    text: 'I strive to be the best version of myself every day.',
    trait: 'conscientiousness',
    type: 'scale',
    isMandatory: false,
    weight: 1,
  },
];

export const categoryLabels: Record<string, string> = {
  personality: 'Personality Traits',
  emotional: 'Emotional Intelligence',
  social: 'Social Tendencies',
  lifestyle: 'Lifestyle Preferences',
  values: 'Values & Beliefs',
  relationship: 'Relationship Style',
  communication: 'Communication',
  intimacy: 'Intimacy & Connection',
  conflict: 'Conflict Resolution',
  future: 'Future & Family',
};

export const getMandatoryQuestions = () => personalityQuestions.filter(q => q.isMandatory);
export const getOptionalQuestions = () => personalityQuestions.filter(q => !q.isMandatory);

export const getQuestionsByCategory = (category: string) => 
  personalityQuestions.filter(q => q.category === category);
