import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { GeneratedList, UserPreferences, GroceryGroup } from './types';
import { groupItemsByCategory, formatQuantity, groupOrder } from './generateGroceryList';

export const exportToPDF = (list: GeneratedList, preferences: UserPreferences) => {
  const doc = new jsPDF();
  const groupedItems = groupItemsByCategory(list.items);
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(34, 139, 34); // Forest green
  doc.text('Smart Grocery List', 105, 20, { align: 'center' });
  
  // Subtitle with preferences
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(
    `${preferences.cuisine} Indian | ${preferences.diet} | ${preferences.budget} Budget | ${preferences.duration} Days | ${preferences.peopleCount} ${preferences.peopleCount === 1 ? 'Person' : 'People'}`,
    105, 28, { align: 'center' }
  );
  
  // Cost estimate
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Estimated Cost: ₹${list.estimatedCost.min} - ₹${list.estimatedCost.max}`, 14, 38);
  
  let yPosition = 45;
  
  // Grocery items by category
  groupOrder.forEach(group => {
    const items = groupedItems[group];
    if (items.length === 0) return;
    
    // Check if we need a new page
    if (yPosition > 260) {
      doc.addPage();
      yPosition = 20;
    }
    
    const tableData = items.map(item => [
      item.name,
      formatQuantity(item.scaledQuantity, item.unit),
      item.useWithin || '-'
    ]);
    
    autoTable(doc, {
      startY: yPosition,
      head: [[group, 'Quantity', 'Use Within']],
      body: tableData,
      theme: 'striped',
      headStyles: { 
        fillColor: [34, 139, 34],
        fontSize: 10,
        fontStyle: 'bold'
      },
      bodyStyles: { fontSize: 9 },
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 40 },
        2: { cellWidth: 50 }
      },
      margin: { left: 14, right: 14 }
    });
    
    yPosition = (doc as any).lastAutoTable.finalY + 8;
  });
  
  // Add Meal Ideas on new page
  doc.addPage();
  yPosition = 20;
  
  doc.setFontSize(16);
  doc.setTextColor(34, 139, 34);
  doc.text('Meal Ideas', 14, yPosition);
  yPosition += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  
  const mealCategories = [
    { name: 'Breakfast', items: list.recipes.breakfast },
    { name: 'Lunch', items: list.recipes.lunch },
    { name: 'Dinner', items: list.recipes.dinner },
    { name: 'Snacks', items: list.recipes.snacks }
  ];
  
  mealCategories.forEach(category => {
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text(`${category.name}:`, 14, yPosition);
    yPosition += 6;
    
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    const itemsText = category.items.join(', ');
    const lines = doc.splitTextToSize(itemsText, 180);
    doc.text(lines, 14, yPosition);
    yPosition += lines.length * 5 + 8;
  });
  
  // Storage Tips
  if (list.storageTips.length > 0) {
    yPosition += 5;
    doc.setFontSize(14);
    doc.setTextColor(34, 139, 34);
    doc.text('Storage Tips', 14, yPosition);
    yPosition += 8;
    
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    
    list.storageTips.forEach(tip => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }
      doc.setFont(undefined, 'bold');
      doc.text(`${tip.item}:`, 14, yPosition);
      doc.setFont(undefined, 'normal');
      const tipLines = doc.splitTextToSize(tip.tip, 160);
      doc.text(tipLines, 50, yPosition);
      yPosition += tipLines.length * 4 + 5;
    });
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by HealthyPlates - Smart Grocery List Generator', 105, 290, { align: 'center' });
    doc.text(`Page ${i} of ${pageCount}`, 195, 290, { align: 'right' });
  }
  
  doc.save(`grocery-list-${preferences.duration}days-${preferences.diet.toLowerCase()}.pdf`);
};

export const exportToExcel = (list: GeneratedList, preferences: UserPreferences) => {
  const groupedItems = groupItemsByCategory(list.items);
  const workbook = XLSX.utils.book_new();
  
  // Main Grocery List Sheet
  const groceryData: any[] = [];
  
  // Header info
  groceryData.push(['Smart Grocery List']);
  groceryData.push([`${preferences.cuisine} Indian | ${preferences.diet} | ${preferences.budget} Budget | ${preferences.duration} Days | ${preferences.peopleCount} Person(s)`]);
  groceryData.push([`Estimated Cost: ₹${list.estimatedCost.min} - ₹${list.estimatedCost.max}`]);
  groceryData.push([]);
  
  // Items by category
  groupOrder.forEach(group => {
    const items = groupedItems[group];
    if (items.length === 0) return;
    
    groceryData.push([group]);
    groceryData.push(['Item', 'Quantity', 'Use Within', 'Storage']);
    
    items.forEach(item => {
      groceryData.push([
        item.name,
        formatQuantity(item.scaledQuantity, item.unit),
        item.useWithin || '-',
        item.storage
      ]);
    });
    groceryData.push([]);
  });
  
  const grocerySheet = XLSX.utils.aoa_to_sheet(groceryData);
  
  // Set column widths
  grocerySheet['!cols'] = [
    { wch: 30 },
    { wch: 15 },
    { wch: 15 },
    { wch: 20 }
  ];
  
  XLSX.utils.book_append_sheet(workbook, grocerySheet, 'Grocery List');
  
  // Meal Ideas Sheet
  const mealData: any[] = [];
  mealData.push(['Meal Ideas']);
  mealData.push([]);
  
  mealData.push(['Breakfast']);
  list.recipes.breakfast.forEach(item => mealData.push([item]));
  mealData.push([]);
  
  mealData.push(['Lunch']);
  list.recipes.lunch.forEach(item => mealData.push([item]));
  mealData.push([]);
  
  mealData.push(['Dinner']);
  list.recipes.dinner.forEach(item => mealData.push([item]));
  mealData.push([]);
  
  mealData.push(['Snacks']);
  list.recipes.snacks.forEach(item => mealData.push([item]));
  
  const mealSheet = XLSX.utils.aoa_to_sheet(mealData);
  mealSheet['!cols'] = [{ wch: 40 }];
  XLSX.utils.book_append_sheet(workbook, mealSheet, 'Meal Ideas');
  
  // Storage Tips Sheet
  const tipsData: any[] = [];
  tipsData.push(['Storage Tips']);
  tipsData.push([]);
  tipsData.push(['Item', 'Priority', 'Tip']);
  
  list.storageTips.forEach(tip => {
    tipsData.push([tip.item, tip.priority, tip.tip]);
  });
  
  const tipsSheet = XLSX.utils.aoa_to_sheet(tipsData);
  tipsSheet['!cols'] = [
    { wch: 25 },
    { wch: 10 },
    { wch: 50 }
  ];
  XLSX.utils.book_append_sheet(workbook, tipsSheet, 'Storage Tips');
  
  // Substitutions Sheet
  if (list.substitutions.length > 0) {
    const subData: any[] = [];
    subData.push(['Smart Substitutions']);
    subData.push([]);
    subData.push(['Original', 'Substitute', 'Reason']);
    
    list.substitutions.forEach(sub => {
      subData.push([sub.original, sub.substitute, sub.reason]);
    });
    
    const subSheet = XLSX.utils.aoa_to_sheet(subData);
    subSheet['!cols'] = [
      { wch: 20 },
      { wch: 20 },
      { wch: 40 }
    ];
    XLSX.utils.book_append_sheet(workbook, subSheet, 'Substitutions');
  }
  
  XLSX.writeFile(workbook, `grocery-list-${preferences.duration}days-${preferences.diet.toLowerCase()}.xlsx`);
};
