// PDF and Excel Export Utilities

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { MealPlan, UserIntake, CalculatedTargets } from './types';

// Generate PDF
export function generatePDF(mealPlan: MealPlan, intake: UserIntake): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;

  // Helper function to add page break if needed
  const checkPageBreak = (requiredSpace: number = 30) => {
    if (yPos + requiredSpace > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      yPos = 20;
    }
  };

  // Cover Page
  doc.setFontSize(28);
  doc.setTextColor(34, 139, 34); // Forest green
  doc.text('Health & Diet Plan', pageWidth / 2, 60, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Personalized Nutrition Plan', pageWidth / 2, 75, { align: 'center' });

  doc.setFontSize(12);
  doc.text(`Goal: ${mealPlan.userSummary.goal}`, pageWidth / 2, 100, { align: 'center' });
  doc.text(`Duration: ${mealPlan.userSummary.planLength}`, pageWidth / 2, 110, { align: 'center' });
  doc.text(`Start Date: ${mealPlan.userSummary.startDate}`, pageWidth / 2, 120, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by HealthyPlates', pageWidth / 2, 280, { align: 'center' });

  // Summary Page
  doc.addPage();
  yPos = 20;
  
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text('Daily Nutrition Targets', 14, yPos);
  yPos += 15;

  const targets = mealPlan.userSummary.dailyTargets;
  
  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Value']],
    body: [
      ['Daily Calories', `${targets.targetCalories} kcal`],
      ['Protein', `${targets.proteinGrams}g`],
      ['Carbohydrates', `${targets.carbsGrams}g`],
      ['Fat', `${targets.fatGrams}g`],
      ['BMR (Basal Metabolic Rate)', `${targets.bmr} kcal`],
      ['TDEE (Total Daily Energy)', `${targets.tdee} kcal`],
      ['Weekly Weight Change', `${targets.weeklyWeightChangeKg > 0 ? '+' : ''}${targets.weeklyWeightChangeKg} kg`],
    ],
    theme: 'striped',
    headStyles: { fillColor: [34, 139, 34] },
  });

  yPos = (doc as any).lastAutoTable.finalY + 20;

  // Condition Notes (if any)
  if (mealPlan.conditionNotes.length > 0) {
    checkPageBreak(50);
    doc.setFontSize(14);
    doc.text('Health Condition Guidelines', 14, yPos);
    yPos += 10;

    doc.setFontSize(10);
    mealPlan.conditionNotes.forEach(note => {
      checkPageBreak(15);
      const lines = doc.splitTextToSize(note, pageWidth - 28);
      doc.text(lines, 14, yPos);
      yPos += lines.length * 6 + 5;
    });
  }

  // Tips
  checkPageBreak(50);
  yPos += 10;
  doc.setFontSize(14);
  doc.text('Lifestyle Tips', 14, yPos);
  yPos += 10;

  doc.setFontSize(10);
  mealPlan.tips.forEach(tip => {
    checkPageBreak(12);
    const lines = doc.splitTextToSize(tip, pageWidth - 28);
    doc.text(lines, 14, yPos);
    yPos += lines.length * 6 + 3;
  });

  // Weekly Meal Plans (show first 7 days as sample)
  doc.addPage();
  yPos = 20;
  doc.setFontSize(18);
  doc.text('Weekly Meal Plan', 14, yPos);
  yPos += 15;

  const daysToShow = Math.min(mealPlan.days.length, 7);
  
  for (let i = 0; i < daysToShow; i++) {
    const day = mealPlan.days[i];
    checkPageBreak(60);

    doc.setFontSize(12);
    doc.setTextColor(34, 139, 34);
    doc.text(`${day.dayName} (${day.date})`, 14, yPos);
    yPos += 8;

    const mealData = day.meals.map(meal => [
      meal.name,
      meal.recipeName,
      `${meal.portionGrams}g`,
      `${meal.kcal}`,
      `${meal.proteinG}g`,
      `${meal.carbsG}g`,
      `${meal.fatG}g`,
    ]);

    mealData.push([
      'TOTAL',
      '',
      '',
      `${day.totalKcal}`,
      `${day.totalProtein}g`,
      `${day.totalCarbs}g`,
      `${day.totalFat}g`,
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Meal', 'Recipe', 'Portion', 'Kcal', 'Protein', 'Carbs', 'Fat']],
      body: mealData,
      theme: 'grid',
      headStyles: { fillColor: [34, 139, 34], fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 50 },
        2: { cellWidth: 20 },
        3: { cellWidth: 18 },
        4: { cellWidth: 20 },
        5: { cellWidth: 18 },
        6: { cellWidth: 18 },
      },
    });

    yPos = (doc as any).lastAutoTable.finalY + 10;
  }

  // Shopping List (Week 1)
  if (mealPlan.weeklyShoppingLists.length > 0) {
    doc.addPage();
    yPos = 20;
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text('Week 1 Shopping List', 14, yPos);
    yPos += 15;

    const shoppingList = mealPlan.weeklyShoppingLists[0];
    shoppingList.items.forEach(category => {
      checkPageBreak(30);
      doc.setFontSize(12);
      doc.setTextColor(34, 139, 34);
      doc.text(category.category, 14, yPos);
      yPos += 8;

      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      const items = category.ingredients.map(ing => `• ${ing.name}`).join('\n');
      const lines = doc.splitTextToSize(items, pageWidth - 28);
      doc.text(lines, 18, yPos);
      yPos += lines.length * 5 + 8;
    });
  }

  // Disclaimer
  doc.addPage();
  yPos = 20;
  doc.setFontSize(14);
  doc.text('Important Disclaimer', 14, yPos);
  yPos += 15;

  doc.setFontSize(10);
  const disclaimer = `This meal plan is for informational and educational purposes only. It does not substitute professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider, registered dietitian, or nutritionist before starting any new diet plan, especially if you have existing medical conditions.

The calorie and macro calculations are estimates based on standard formulas and may vary based on individual metabolism and other factors. Monitor your progress and adjust as needed.

If you experience any adverse effects, discontinue the plan and consult a healthcare professional immediately.

Generated by HealthyPlates - ${new Date().toLocaleDateString()}`;

  const disclaimerLines = doc.splitTextToSize(disclaimer, pageWidth - 28);
  doc.text(disclaimerLines, 14, yPos);

  // Save the PDF
  doc.save(`HealthyPlates_MealPlan_${mealPlan.userSummary.startDate}.pdf`);
}

// Generate Excel
export function generateExcel(mealPlan: MealPlan, intake: UserIntake): void {
  const workbook = XLSX.utils.book_new();

  // Summary Sheet
  const summaryData = [
    ['Health & Diet Plan - Summary'],
    [],
    ['Goal', mealPlan.userSummary.goal],
    ['Plan Duration', mealPlan.userSummary.planLength],
    ['Start Date', mealPlan.userSummary.startDate],
    [],
    ['Daily Nutrition Targets'],
    ['Daily Calories', `${mealPlan.userSummary.dailyTargets.targetCalories} kcal`],
    ['Protein', `${mealPlan.userSummary.dailyTargets.proteinGrams}g`],
    ['Carbohydrates', `${mealPlan.userSummary.dailyTargets.carbsGrams}g`],
    ['Fat', `${mealPlan.userSummary.dailyTargets.fatGrams}g`],
    [],
    ['Calculation Details'],
    ['BMR (Basal Metabolic Rate)', `${mealPlan.userSummary.dailyTargets.bmr} kcal`],
    ['TDEE (Total Daily Energy)', `${mealPlan.userSummary.dailyTargets.tdee} kcal`],
    ['Weekly Weight Change', `${mealPlan.userSummary.dailyTargets.weeklyWeightChangeKg} kg`],
    [],
    ['User Profile'],
    ['Sex', intake.profile.sex],
    ['Age', intake.profile.age],
    ['Height', `${intake.profile.heightCm} cm`],
    ['Weight', `${intake.profile.weightKg} kg`],
    ['Activity Level', intake.activity.activityLevel],
    ['Meals per Day', intake.activity.mealsPerDay],
  ];

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

  // Meal Plan Sheet
  const mealPlanData = [
    ['Day', 'Date', 'Day Name', 'Meal', 'Recipe', 'Portion (g)', 'Calories', 'Protein (g)', 'Carbs (g)', 'Fat (g)'],
  ];

  mealPlan.days.forEach(day => {
    day.meals.forEach(meal => {
      mealPlanData.push([
        day.day.toString(),
        day.date,
        day.dayName,
        meal.name,
        meal.recipeName,
        meal.portionGrams.toString(),
        meal.kcal.toString(),
        meal.proteinG.toString(),
        meal.carbsG.toString(),
        meal.fatG.toString(),
      ]);
    });
    // Add daily total row
    mealPlanData.push([
      day.day.toString(),
      day.date,
      day.dayName,
      'DAILY TOTAL',
      '',
      '',
      day.totalKcal.toString(),
      day.totalProtein.toString(),
      day.totalCarbs.toString(),
      day.totalFat.toString(),
    ]);
  });

  const mealPlanSheet = XLSX.utils.aoa_to_sheet(mealPlanData);
  XLSX.utils.book_append_sheet(workbook, mealPlanSheet, 'Meal Plan');

  // Ingredients Sheet (Shopping Lists)
  const ingredientsData = [
    ['Week', 'Category', 'Ingredient', 'Quantity'],
  ];

  mealPlan.weeklyShoppingLists.forEach(week => {
    week.items.forEach(category => {
      category.ingredients.forEach(ing => {
        ingredientsData.push([
          `Week ${week.weekNumber}`,
          category.category,
          ing.name,
          ing.quantity,
        ]);
      });
    });
  });

  const ingredientsSheet = XLSX.utils.aoa_to_sheet(ingredientsData);
  XLSX.utils.book_append_sheet(workbook, ingredientsSheet, 'Shopping List');

  // Recipes Sheet
  const recipesData = [
    ['Recipe Name', 'Ingredients', 'Instructions', 'Prep Time (mins)'],
  ];

  const uniqueRecipes = new Map<string, { ingredients: string[]; instructions: string[]; prepTime: number }>();
  mealPlan.days.forEach(day => {
    day.meals.forEach(meal => {
      if (!uniqueRecipes.has(meal.recipeName)) {
        uniqueRecipes.set(meal.recipeName, {
          ingredients: meal.ingredients,
          instructions: meal.instructions,
          prepTime: meal.prepTime,
        });
      }
    });
  });

  uniqueRecipes.forEach((recipe, name) => {
    recipesData.push([
      name,
      recipe.ingredients.join('; '),
      recipe.instructions.join(' → '),
      recipe.prepTime.toString(),
    ]);
  });

  const recipesSheet = XLSX.utils.aoa_to_sheet(recipesData);
  XLSX.utils.book_append_sheet(workbook, recipesSheet, 'Recipes');

  // Tips & Notes Sheet
  const notesData = [
    ['Health Condition Guidelines'],
    ...mealPlan.conditionNotes.map(note => [note]),
    [],
    ['Lifestyle Tips'],
    ...mealPlan.tips.map(tip => [tip]),
    [],
    ['Disclaimer'],
    ['This meal plan is for informational purposes only and does not substitute professional medical advice.'],
    ['Always consult with a healthcare provider before starting any new diet plan.'],
  ];

  const notesSheet = XLSX.utils.aoa_to_sheet(notesData);
  XLSX.utils.book_append_sheet(workbook, notesSheet, 'Notes');

  // Save the Excel file
  XLSX.writeFile(workbook, `HealthyPlates_MealPlan_${mealPlan.userSummary.startDate}.xlsx`);
}
