// PDF and Excel Export Utilities

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { MealPlan, UserIntake, CalculatedTargets } from './types';

// Generate PDF
export function generatePDF(mealPlan: MealPlan, intake: UserIntake): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;

  // Helper function to add page break if needed
  const checkPageBreak = (requiredSpace: number = 30) => {
    if (yPos + requiredSpace > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      yPos = 20;
    }
  };

  // Cover Page
  doc.setFontSize(28);
  doc.setTextColor(34, 139, 34); // Forest green
  doc.text('Health & Diet Plan', pageWidth / 2, 60, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Personalized Nutrition Plan', pageWidth / 2, 75, { align: 'center' });

  doc.setFontSize(12);
  doc.text(`Goal: ${mealPlan.userSummary.goal}`, pageWidth / 2, 100, { align: 'center' });
  doc.text(`Duration: ${mealPlan.userSummary.planLength}`, pageWidth / 2, 110, { align: 'center' });
  doc.text(`Start Date: ${mealPlan.userSummary.startDate}`, pageWidth / 2, 120, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by HealthyPlates', pageWidth / 2, 280, { align: 'center' });

  // Summary Page
  doc.addPage();
  yPos = 20;
  
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text('Daily Nutrition Targets', 14, yPos);
  yPos += 15;

  const targets = mealPlan.userSummary.dailyTargets;
  
  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Value']],
    body: [
      ['Daily Calories', `${targets.targetCalories} kcal`],
      ['Protein', `${targets.proteinGrams}g`],
      ['Carbohydrates', `${targets.carbsGrams}g`],
      ['Fat', `${targets.fatGrams}g`],
      ['BMR (Basal Metabolic Rate)', `${targets.bmr} kcal`],
      ['TDEE (Total Daily Energy)', `${targets.tdee} kcal`],
      ['Weekly Weight Change', `${targets.weeklyWeightChangeKg > 0 ? '+' : ''}${targets.weeklyWeightChangeKg} kg`],
    ],
    theme: 'striped',
    headStyles: { fillColor: [34, 139, 34] },
  });

  yPos = (doc as any).lastAutoTable.finalY + 20;

  // User Profile Summary
  checkPageBreak(80);
  doc.setFontSize(14);
  doc.text('User Profile Summary', 14, yPos);
  yPos += 10;

  autoTable(doc, {
    startY: yPos,
    head: [['Attribute', 'Value']],
    body: [
      ['Sex', intake.profile.sex.charAt(0).toUpperCase() + intake.profile.sex.slice(1)],
      ['Age', `${intake.profile.age} years`],
      ['Height', `${intake.profile.heightCm} cm`],
      ['Weight', `${intake.profile.weightKg} kg`],
      ['Body Type', intake.profile.bodyType ? intake.profile.bodyType.charAt(0).toUpperCase() + intake.profile.bodyType.slice(1) : 'Not specified'],
      ['Activity Level', intake.activity.activityLevel.charAt(0).toUpperCase() + intake.activity.activityLevel.slice(1)],
      ['Meals per Day', intake.activity.mealsPerDay.toString()],
      ['Diet Types', intake.dietary.dietTypes.join(', ') || 'Not specified'],
      ['Cuisine Preferences', intake.dietary.cuisinePrefs.join(', ') || 'Not specified'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [34, 139, 34] },
  });

  yPos = (doc as any).lastAutoTable.finalY + 20;

  // Condition Notes (if any)
  if (mealPlan.conditionNotes.length > 0) {
    checkPageBreak(50);
    doc.setFontSize(14);
    doc.text('Health Condition Guidelines', 14, yPos);
    yPos += 10;

    doc.setFontSize(10);
    mealPlan.conditionNotes.forEach((note, index) => {
      checkPageBreak(15);
      const bulletNumber = `${index + 1}. `;
      const lines = doc.splitTextToSize(bulletNumber + note, pageWidth - 28);
      doc.text(lines, 14, yPos);
      yPos += lines.length * 6 + 5;
    });
  }

  // Tips - Fixed bullet points
  checkPageBreak(50);
  yPos += 10;
  doc.setFontSize(14);
  doc.text('Lifestyle Tips', 14, yPos);
  yPos += 10;

  doc.setFontSize(10);
  mealPlan.tips.forEach((tip, index) => {
    checkPageBreak(12);
    // Use numbered list instead of bullet symbols to avoid encoding issues
    const bulletNumber = `${index + 1}. `;
    const lines = doc.splitTextToSize(bulletNumber + tip, pageWidth - 28);
    doc.text(lines, 14, yPos);
    yPos += lines.length * 6 + 3;
  });

  // Full Meal Plan - All Days
  doc.addPage();
  yPos = 20;
  doc.setFontSize(18);
  doc.text(`Complete Meal Plan (${mealPlan.days.length} Days)`, 14, yPos);
  yPos += 15;

  // Show ALL days based on plan length
  for (let i = 0; i < mealPlan.days.length; i++) {
    const day = mealPlan.days[i];
    checkPageBreak(60);

    doc.setFontSize(12);
    doc.setTextColor(34, 139, 34);
    doc.text(`Day ${day.day}: ${day.dayName} (${day.date})`, 14, yPos);
    yPos += 8;

    const mealData = day.meals.map(meal => [
      meal.name,
      meal.recipeName,
      `${meal.portionGrams}g`,
      `${meal.kcal}`,
      `${meal.proteinG}g`,
      `${meal.carbsG}g`,
      `${meal.fatG}g`,
    ]);

    mealData.push([
      'TOTAL',
      '',
      '',
      `${day.totalKcal}`,
      `${day.totalProtein}g`,
      `${day.totalCarbs}g`,
      `${day.totalFat}g`,
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Meal', 'Recipe', 'Portion', 'Kcal', 'Protein', 'Carbs', 'Fat']],
      body: mealData,
      theme: 'grid',
      headStyles: { fillColor: [34, 139, 34], fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 50 },
        2: { cellWidth: 20 },
        3: { cellWidth: 18 },
        4: { cellWidth: 20 },
        5: { cellWidth: 18 },
        6: { cellWidth: 18 },
      },
    });

    yPos = (doc as any).lastAutoTable.finalY + 10;
  }

  // Shopping Lists - All Weeks
  if (mealPlan.weeklyShoppingLists.length > 0) {
    mealPlan.weeklyShoppingLists.forEach((shoppingList, weekIndex) => {
      doc.addPage();
      yPos = 20;
      doc.setFontSize(18);
      doc.setTextColor(0, 0, 0);
      doc.text(`Week ${shoppingList.weekNumber} Shopping List`, 14, yPos);
      yPos += 15;

      shoppingList.items.forEach(category => {
        checkPageBreak(30);
        doc.setFontSize(12);
        doc.setTextColor(34, 139, 34);
        doc.text(category.category, 14, yPos);
        yPos += 8;

        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        category.ingredients.forEach((ing, idx) => {
          checkPageBreak(8);
          doc.text(`${idx + 1}. ${ing.name} - ${ing.quantity}`, 18, yPos);
          yPos += 6;
        });
        yPos += 4;
      });
    });
  }

  // Recipes Page - All unique recipes from entire plan
  doc.addPage();
  yPos = 20;
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text('Recipe Details', 14, yPos);
  yPos += 15;

  const uniqueRecipes = new Map<string, { ingredients: string[]; instructions: string[]; prepTime: number }>();
  mealPlan.days.forEach(day => {
    day.meals.forEach(meal => {
      if (!uniqueRecipes.has(meal.recipeName)) {
        uniqueRecipes.set(meal.recipeName, {
          ingredients: meal.ingredients,
          instructions: meal.instructions,
          prepTime: meal.prepTime,
        });
      }
    });
  });

  uniqueRecipes.forEach((recipe, name) => {
    checkPageBreak(60);
    
    doc.setFontSize(12);
    doc.setTextColor(34, 139, 34);
    doc.text(name, 14, yPos);
    yPos += 7;

    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(`Prep Time: ${recipe.prepTime} minutes`, 14, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text('Ingredients:', 14, yPos);
    yPos += 6;

    recipe.ingredients.forEach((ing, idx) => {
      checkPageBreak(6);
      doc.text(`  ${idx + 1}. ${ing}`, 16, yPos);
      yPos += 5;
    });
    yPos += 4;

    doc.text('Instructions:', 14, yPos);
    yPos += 6;

    recipe.instructions.forEach((step, idx) => {
      checkPageBreak(10);
      const lines = doc.splitTextToSize(`${idx + 1}. ${step}`, pageWidth - 34);
      doc.text(lines, 18, yPos);
      yPos += lines.length * 5 + 2;
    });

    yPos += 10;
  });

  // Disclaimer
  doc.addPage();
  yPos = 20;
  doc.setFontSize(14);
  doc.text('Important Disclaimer', 14, yPos);
  yPos += 15;

  doc.setFontSize(10);
  const disclaimer = `This meal plan is for informational and educational purposes only. It does not substitute professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider, registered dietitian, or nutritionist before starting any new diet plan, especially if you have existing medical conditions.

The calorie and macro calculations are estimates based on standard formulas and may vary based on individual metabolism and other factors. Monitor your progress and adjust as needed.

If you experience any adverse effects, discontinue the plan and consult a healthcare professional immediately.

Generated by HealthyPlates - ${new Date().toLocaleDateString()}`;

  const disclaimerLines = doc.splitTextToSize(disclaimer, pageWidth - 28);
  doc.text(disclaimerLines, 14, yPos);

  // Save the PDF
  doc.save(`HealthyPlates_MealPlan_${mealPlan.userSummary.startDate}.pdf`);
}

// Generate Excel - Enhanced with all PDF content
export function generateExcel(mealPlan: MealPlan, intake: UserIntake): void {
  const workbook = XLSX.utils.book_new();

  // Summary Sheet - Enhanced
  const summaryData = [
    ['Health & Diet Plan - Summary'],
    [],
    ['=== Plan Overview ==='],
    ['Goal', mealPlan.userSummary.goal],
    ['Plan Duration', mealPlan.userSummary.planLength],
    ['Start Date', mealPlan.userSummary.startDate],
    [],
    ['=== Daily Nutrition Targets ==='],
    ['Daily Calories', `${mealPlan.userSummary.dailyTargets.targetCalories} kcal`],
    ['Protein', `${mealPlan.userSummary.dailyTargets.proteinGrams}g`],
    ['Carbohydrates', `${mealPlan.userSummary.dailyTargets.carbsGrams}g`],
    ['Fat', `${mealPlan.userSummary.dailyTargets.fatGrams}g`],
    [],
    ['=== Calculation Details ==='],
    ['BMR (Basal Metabolic Rate)', `${mealPlan.userSummary.dailyTargets.bmr} kcal`],
    ['TDEE (Total Daily Energy)', `${mealPlan.userSummary.dailyTargets.tdee} kcal`],
    ['Deficit/Surplus', `${mealPlan.userSummary.dailyTargets.deficitOrSurplus} kcal`],
    ['Weekly Weight Change', `${mealPlan.userSummary.dailyTargets.weeklyWeightChangeKg} kg`],
    [],
    ['=== User Profile ==='],
    ['Sex', intake.profile.sex],
    ['Age', `${intake.profile.age} years`],
    ['Height', `${intake.profile.heightCm} cm`],
    ['Weight', `${intake.profile.weightKg} kg`],
    ['Body Type', intake.profile.bodyType || 'Not specified'],
    ['Body Fat %', intake.profile.bodyFatPercent ? `${intake.profile.bodyFatPercent}%` : 'Not specified'],
    [],
    ['=== Activity & Routine ==='],
    ['Activity Level', intake.activity.activityLevel],
    ['Steps per Day', intake.activity.stepsPerDay || 'Not specified'],
    ['Meals per Day', intake.activity.mealsPerDay],
    [],
    ['=== Dietary Preferences ==='],
    ['Diet Types', intake.dietary.dietTypes.join(', ') || 'Not specified'],
    ['Cuisine Preferences', intake.dietary.cuisinePrefs.join(', ') || 'Not specified'],
    ['Religious Restrictions', intake.dietary.religiousRestrictions.join(', ') || 'None'],
    ['Spice Preference', intake.dietary.spicePreference],
    ['Allergies', intake.dietary.allergies.join(', ') || 'None'],
    ['Foods to Avoid', intake.dietary.dislikes || 'None'],
    ['Budget', intake.dietary.budget],
    ['Cooking Time', `${intake.dietary.cookingTime} minutes`],
    ['Kitchen Equipment', intake.dietary.equipment.join(', ') || 'Not specified'],
    [],
    ['=== Medical Information ==='],
    ['Health Conditions', intake.medical.conditions.join(', ') || 'None'],
    ['Medications', intake.medical.medications || 'None'],
    ['Doctor Restrictions', intake.medical.doctorRestrictions || 'None'],
    ['Sleep Hours', `${intake.medical.sleepHours} hours/night`],
    ['Stress Level', intake.medical.stressLevel],
  ];

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  // Set column widths
  summarySheet['!cols'] = [{ wch: 30 }, { wch: 50 }];
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

  // Meal Plan Sheet
  const mealPlanData = [
    ['Day', 'Date', 'Day Name', 'Meal', 'Recipe', 'Portion (g)', 'Calories', 'Protein (g)', 'Carbs (g)', 'Fat (g)'],
  ];

  mealPlan.days.forEach(day => {
    day.meals.forEach(meal => {
      mealPlanData.push([
        day.day.toString(),
        day.date,
        day.dayName,
        meal.name,
        meal.recipeName,
        meal.portionGrams.toString(),
        meal.kcal.toString(),
        meal.proteinG.toString(),
        meal.carbsG.toString(),
        meal.fatG.toString(),
      ]);
    });
    // Add daily total row
    mealPlanData.push([
      day.day.toString(),
      day.date,
      day.dayName,
      'DAILY TOTAL',
      '',
      '',
      day.totalKcal.toString(),
      day.totalProtein.toString(),
      day.totalCarbs.toString(),
      day.totalFat.toString(),
    ]);
  });

  const mealPlanSheet = XLSX.utils.aoa_to_sheet(mealPlanData);
  mealPlanSheet['!cols'] = [
    { wch: 6 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, 
    { wch: 35 }, { wch: 12 }, { wch: 10 }, { wch: 12 }, { wch: 10 }, { wch: 10 }
  ];
  XLSX.utils.book_append_sheet(workbook, mealPlanSheet, 'Meal Plan');

  // Ingredients Sheet (Shopping Lists)
  const ingredientsData = [
    ['Week', 'Category', 'Ingredient', 'Quantity'],
  ];

  mealPlan.weeklyShoppingLists.forEach(week => {
    week.items.forEach(category => {
      category.ingredients.forEach(ing => {
        ingredientsData.push([
          `Week ${week.weekNumber}`,
          category.category,
          ing.name,
          ing.quantity,
        ]);
      });
    });
  });

  const ingredientsSheet = XLSX.utils.aoa_to_sheet(ingredientsData);
  ingredientsSheet['!cols'] = [{ wch: 10 }, { wch: 20 }, { wch: 30 }, { wch: 20 }];
  XLSX.utils.book_append_sheet(workbook, ingredientsSheet, 'Shopping List');

  // Recipes Sheet - Enhanced
  const recipesData = [
    ['Recipe Name', 'Prep Time (mins)', 'Ingredients', 'Instructions'],
  ];

  const uniqueRecipes = new Map<string, { ingredients: string[]; instructions: string[]; prepTime: number }>();
  mealPlan.days.forEach(day => {
    day.meals.forEach(meal => {
      if (!uniqueRecipes.has(meal.recipeName)) {
        uniqueRecipes.set(meal.recipeName, {
          ingredients: meal.ingredients,
          instructions: meal.instructions,
          prepTime: meal.prepTime,
        });
      }
    });
  });

  uniqueRecipes.forEach((recipe, name) => {
    recipesData.push([
      name,
      recipe.prepTime.toString(),
      recipe.ingredients.map((ing, i) => `${i + 1}. ${ing}`).join('\n'),
      recipe.instructions.map((step, i) => `${i + 1}. ${step}`).join('\n'),
    ]);
  });

  const recipesSheet = XLSX.utils.aoa_to_sheet(recipesData);
  recipesSheet['!cols'] = [{ wch: 30 }, { wch: 15 }, { wch: 50 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(workbook, recipesSheet, 'Recipes');

  // Tips & Notes Sheet - Enhanced
  const notesData: (string | undefined)[][] = [
    ['=== Health Condition Guidelines ==='],
  ];
  
  if (mealPlan.conditionNotes.length > 0) {
    mealPlan.conditionNotes.forEach((note, idx) => {
      notesData.push([`${idx + 1}. ${note}`]);
    });
  } else {
    notesData.push(['No specific condition guidelines']);
  }
  
  notesData.push([]);
  notesData.push(['=== Lifestyle Tips ===']);
  mealPlan.tips.forEach((tip, idx) => {
    notesData.push([`${idx + 1}. ${tip}`]);
  });
  
  notesData.push([]);
  notesData.push(['=== Important Disclaimer ===']);
  notesData.push(['This meal plan is for informational and educational purposes only.']);
  notesData.push(['It does not substitute professional medical advice, diagnosis, or treatment.']);
  notesData.push(['Always consult with a qualified healthcare provider before starting any new diet plan.']);
  notesData.push(['Monitor your progress and adjust as needed.']);
  notesData.push([]);
  notesData.push([`Generated by HealthyPlates on ${new Date().toLocaleDateString()}`]);

  const notesSheet = XLSX.utils.aoa_to_sheet(notesData);
  notesSheet['!cols'] = [{ wch: 100 }];
  XLSX.utils.book_append_sheet(workbook, notesSheet, 'Notes & Tips');

  // Save the Excel file
  XLSX.writeFile(workbook, `HealthyPlates_MealPlan_${mealPlan.userSummary.startDate}.xlsx`);
}
