// Recipe Database for Meal Plan Generation

export interface Recipe {
  id: string;
  name: string;
  cuisine: string;
  isVegetarian: boolean;
  isVegan: boolean;
  allergens: string[];
  tags: string[];
  macrosPer100g: {
    kcal: number;
    protein: number;
    carbs: number;
    fat: number;
    fiber: number;
  };
  defaultPortionG: number;
  prepTimeMinutes: number;
  equipment: string[];
  costTier: 'low' | 'medium' | 'high';
  conditionFlags: {
    diabetes_ok: boolean;
    thyroid_ok: boolean;
    bp_ok: boolean;
  };
  mealType: 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'any';
  ingredients: string[];
  instructions: string[];
}

export const recipeDatabase: Recipe[] = [
  // BREAKFAST OPTIONS
  {
    id: 'oats-banana',
    name: 'Oatmeal with Banana & Nuts',
    cuisine: 'international',
    isVegetarian: true,
    isVegan: false,
    allergens: ['nuts', 'gluten'],
    tags: ['high-fiber', 'whole-grain', 'low-gi'],
    macrosPer100g: { kcal: 150, protein: 5, carbs: 25, fat: 4, fiber: 4 },
    defaultPortionG: 250,
    prepTimeMinutes: 10,
    equipment: ['stove'],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'breakfast',
    ingredients: ['Rolled oats 50g', 'Milk 150ml', 'Banana 1 medium', 'Almonds 10g', 'Honey 1 tsp'],
    instructions: ['Boil milk', 'Add oats and cook for 5 mins', 'Top with sliced banana and nuts', 'Drizzle honey if desired'],
  },
  {
    id: 'poha',
    name: 'Vegetable Poha',
    cuisine: 'indian-north',
    isVegetarian: true,
    isVegan: true,
    allergens: [],
    tags: ['low-gi', 'light'],
    macrosPer100g: { kcal: 130, protein: 3, carbs: 22, fat: 3, fiber: 2 },
    defaultPortionG: 200,
    prepTimeMinutes: 15,
    equipment: ['stove'],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'breakfast',
    ingredients: ['Flattened rice (Poha) 100g', 'Onion 1 medium', 'Potato 1 small', 'Peanuts 20g', 'Curry leaves', 'Turmeric', 'Mustard seeds', 'Green chili'],
    instructions: ['Rinse poha and drain', 'Sauté mustard seeds and curry leaves', 'Add onions and potatoes', 'Add poha with turmeric', 'Garnish with coriander and lemon'],
  },
  {
    id: 'idli-sambar',
    name: 'Idli with Sambar',
    cuisine: 'indian-south',
    isVegetarian: true,
    isVegan: true,
    allergens: [],
    tags: ['fermented', 'probiotic', 'low-fat'],
    macrosPer100g: { kcal: 110, protein: 4, carbs: 20, fat: 1, fiber: 3 },
    defaultPortionG: 300,
    prepTimeMinutes: 20,
    equipment: ['steamer', 'stove'],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'breakfast',
    ingredients: ['Idli batter 200g', 'Sambar 150ml', 'Mixed vegetables', 'Sambar powder', 'Tamarind', 'Toor dal'],
    instructions: ['Steam idli batter in molds for 12 mins', 'Prepare sambar with vegetables and dal', 'Serve idlis hot with sambar'],
  },
  {
    id: 'egg-toast',
    name: 'Scrambled Eggs on Whole Wheat Toast',
    cuisine: 'international',
    isVegetarian: true,
    isVegan: false,
    allergens: ['eggs', 'gluten'],
    tags: ['high-protein', 'egg'],
    macrosPer100g: { kcal: 180, protein: 12, carbs: 15, fat: 8, fiber: 2 },
    defaultPortionG: 200,
    prepTimeMinutes: 10,
    equipment: ['stove'],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'breakfast',
    ingredients: ['Eggs 2', 'Whole wheat bread 2 slices', 'Butter 10g', 'Salt & pepper', 'Milk 30ml'],
    instructions: ['Beat eggs with milk', 'Scramble in butter on low heat', 'Toast bread slices', 'Serve eggs on toast'],
  },
  {
    id: 'upma',
    name: 'Vegetable Upma',
    cuisine: 'indian-south',
    isVegetarian: true,
    isVegan: true,
    allergens: ['gluten'],
    tags: ['whole-grain'],
    macrosPer100g: { kcal: 140, protein: 4, carbs: 24, fat: 3, fiber: 2 },
    defaultPortionG: 200,
    prepTimeMinutes: 15,
    equipment: ['stove'],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'breakfast',
    ingredients: ['Semolina (Rava) 100g', 'Mixed vegetables 100g', 'Mustard seeds', 'Curry leaves', 'Cashews 10g', 'Green chili'],
    instructions: ['Dry roast semolina until golden', 'Sauté vegetables with spices', 'Add water and semolina', 'Cook until fluffy'],
  },
  {
    id: 'smoothie-bowl',
    name: 'Protein Smoothie Bowl',
    cuisine: 'international',
    isVegetarian: true,
    isVegan: false,
    allergens: ['dairy'],
    tags: ['high-protein', 'quick'],
    macrosPer100g: { kcal: 120, protein: 8, carbs: 18, fat: 3, fiber: 3 },
    defaultPortionG: 300,
    prepTimeMinutes: 5,
    equipment: ['mixer'],
    costTier: 'medium',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'breakfast',
    ingredients: ['Greek yogurt 150g', 'Banana 1', 'Berries 50g', 'Granola 30g', 'Chia seeds 10g'],
    instructions: ['Blend yogurt with banana', 'Pour into bowl', 'Top with berries, granola, and chia seeds'],
  },

  // LUNCH OPTIONS
  {
    id: 'dal-rice',
    name: 'Dal with Brown Rice',
    cuisine: 'indian',
    isVegetarian: true,
    isVegan: true,
    allergens: [],
    tags: ['high-protein', 'high-fiber', 'complete-protein'],
    macrosPer100g: { kcal: 140, protein: 6, carbs: 24, fat: 2, fiber: 4 },
    defaultPortionG: 350,
    prepTimeMinutes: 30,
    equipment: ['stove', 'pressure-cooker'],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'lunch',
    ingredients: ['Toor dal 100g', 'Brown rice 100g', 'Tomato 1', 'Onion 1', 'Turmeric', 'Cumin', 'Ghee 1 tsp'],
    instructions: ['Pressure cook dal with turmeric', 'Cook brown rice separately', 'Prepare tadka with cumin and tomatoes', 'Serve dal over rice'],
  },
  {
    id: 'chicken-rice',
    name: 'Grilled Chicken with Rice & Vegetables',
    cuisine: 'international',
    isVegetarian: false,
    isVegan: false,
    allergens: [],
    tags: ['high-protein', 'lean-protein'],
    macrosPer100g: { kcal: 160, protein: 18, carbs: 15, fat: 4, fiber: 2 },
    defaultPortionG: 350,
    prepTimeMinutes: 30,
    equipment: ['stove', 'oven'],
    costTier: 'medium',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'lunch',
    ingredients: ['Chicken breast 150g', 'Brown rice 100g', 'Broccoli 100g', 'Olive oil 1 tbsp', 'Herbs & spices'],
    instructions: ['Marinate chicken with herbs', 'Grill or bake for 20 mins', 'Cook rice', 'Steam vegetables', 'Serve together'],
  },
  {
    id: 'paneer-roti',
    name: 'Paneer Bhurji with Whole Wheat Roti',
    cuisine: 'indian-north',
    isVegetarian: true,
    isVegan: false,
    allergens: ['dairy'],
    tags: ['high-protein'],
    macrosPer100g: { kcal: 200, protein: 12, carbs: 18, fat: 10, fiber: 3 },
    defaultPortionG: 300,
    prepTimeMinutes: 25,
    equipment: ['stove'],
    costTier: 'medium',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'lunch',
    ingredients: ['Paneer 150g', 'Whole wheat roti 2', 'Onion 1', 'Tomato 1', 'Green peas 50g', 'Spices'],
    instructions: ['Crumble paneer', 'Sauté onions and tomatoes', 'Add paneer and peas', 'Cook with spices', 'Serve with warm rotis'],
  },
  {
    id: 'rajma-rice',
    name: 'Rajma Chawal (Kidney Beans with Rice)',
    cuisine: 'indian-north',
    isVegetarian: true,
    isVegan: true,
    allergens: [],
    tags: ['high-protein', 'high-fiber', 'comfort-food'],
    macrosPer100g: { kcal: 150, protein: 7, carbs: 26, fat: 2, fiber: 5 },
    defaultPortionG: 350,
    prepTimeMinutes: 45,
    equipment: ['stove', 'pressure-cooker'],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'lunch',
    ingredients: ['Kidney beans 150g', 'Basmati rice 100g', 'Tomato puree', 'Onion', 'Ginger-garlic paste', 'Spices'],
    instructions: ['Soak and pressure cook rajma', 'Prepare masala gravy', 'Add rajma and simmer', 'Serve with steamed rice'],
  },
  {
    id: 'fish-curry',
    name: 'Fish Curry with Rice',
    cuisine: 'indian-south',
    isVegetarian: false,
    isVegan: false,
    allergens: ['fish'],
    tags: ['high-protein', 'omega-3'],
    macrosPer100g: { kcal: 140, protein: 15, carbs: 12, fat: 5, fiber: 1 },
    defaultPortionG: 350,
    prepTimeMinutes: 35,
    equipment: ['stove'],
    costTier: 'medium',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'lunch',
    ingredients: ['Fish fillet 150g', 'Rice 100g', 'Coconut milk 100ml', 'Tamarind', 'Curry leaves', 'Spices'],
    instructions: ['Marinate fish with turmeric', 'Prepare coconut-based curry', 'Add fish and cook gently', 'Serve with rice'],
  },
  {
    id: 'quinoa-salad',
    name: 'Quinoa Vegetable Salad',
    cuisine: 'international',
    isVegetarian: true,
    isVegan: true,
    allergens: [],
    tags: ['high-protein', 'high-fiber', 'complete-protein'],
    macrosPer100g: { kcal: 130, protein: 5, carbs: 20, fat: 4, fiber: 4 },
    defaultPortionG: 300,
    prepTimeMinutes: 20,
    equipment: ['stove'],
    costTier: 'medium',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'lunch',
    ingredients: ['Quinoa 80g', 'Cucumber 50g', 'Tomatoes 50g', 'Bell peppers 50g', 'Olive oil', 'Lemon juice', 'Herbs'],
    instructions: ['Cook quinoa and cool', 'Chop vegetables', 'Mix with dressing', 'Season and serve'],
  },

  // DINNER OPTIONS
  {
    id: 'chicken-curry-roti',
    name: 'Chicken Curry with Multigrain Roti',
    cuisine: 'indian',
    isVegetarian: false,
    isVegan: false,
    allergens: [],
    tags: ['high-protein'],
    macrosPer100g: { kcal: 180, protein: 16, carbs: 16, fat: 6, fiber: 3 },
    defaultPortionG: 350,
    prepTimeMinutes: 40,
    equipment: ['stove'],
    costTier: 'medium',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'dinner',
    ingredients: ['Chicken 200g', 'Multigrain roti 2', 'Onion', 'Tomato', 'Yogurt', 'Spices'],
    instructions: ['Marinate chicken in yogurt and spices', 'Prepare onion-tomato gravy', 'Add chicken and cook until tender', 'Serve with warm rotis'],
  },
  {
    id: 'tofu-stir-fry',
    name: 'Tofu Vegetable Stir-Fry',
    cuisine: 'asian',
    isVegetarian: true,
    isVegan: true,
    allergens: ['soy'],
    tags: ['high-protein', 'low-carb'],
    macrosPer100g: { kcal: 110, protein: 10, carbs: 8, fat: 5, fiber: 3 },
    defaultPortionG: 300,
    prepTimeMinutes: 20,
    equipment: ['stove'],
    costTier: 'medium',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'dinner',
    ingredients: ['Firm tofu 200g', 'Mixed vegetables 200g', 'Soy sauce 1 tbsp', 'Ginger', 'Garlic', 'Sesame oil'],
    instructions: ['Press and cube tofu', 'Stir-fry vegetables', 'Add tofu and sauce', 'Cook until heated through'],
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer with Jeera Rice',
    cuisine: 'indian-north',
    isVegetarian: true,
    isVegan: false,
    allergens: ['dairy'],
    tags: ['high-protein', 'iron-rich'],
    macrosPer100g: { kcal: 170, protein: 10, carbs: 14, fat: 9, fiber: 3 },
    defaultPortionG: 350,
    prepTimeMinutes: 35,
    equipment: ['stove', 'mixer'],
    costTier: 'medium',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'dinner',
    ingredients: ['Paneer 150g', 'Spinach 200g', 'Rice 100g', 'Onion', 'Cream 30ml', 'Cumin', 'Spices'],
    instructions: ['Blanch and puree spinach', 'Sauté cubes of paneer', 'Prepare spinach gravy', 'Add paneer cubes', 'Serve with jeera rice'],
  },
  {
    id: 'grilled-fish',
    name: 'Grilled Fish with Salad',
    cuisine: 'mediterranean',
    isVegetarian: false,
    isVegan: false,
    allergens: ['fish'],
    tags: ['high-protein', 'omega-3', 'low-carb'],
    macrosPer100g: { kcal: 130, protein: 20, carbs: 5, fat: 4, fiber: 2 },
    defaultPortionG: 300,
    prepTimeMinutes: 25,
    equipment: ['oven', 'stove'],
    costTier: 'high',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'dinner',
    ingredients: ['Fish fillet 200g', 'Mixed greens 100g', 'Olive oil', 'Lemon', 'Herbs', 'Cherry tomatoes'],
    instructions: ['Marinate fish with lemon and herbs', 'Grill or bake for 15 mins', 'Prepare fresh salad', 'Serve together'],
  },
  {
    id: 'dal-khichdi',
    name: 'Moong Dal Khichdi',
    cuisine: 'indian',
    isVegetarian: true,
    isVegan: true,
    allergens: [],
    tags: ['easy-digest', 'comfort-food', 'complete-protein'],
    macrosPer100g: { kcal: 120, protein: 5, carbs: 22, fat: 2, fiber: 3 },
    defaultPortionG: 300,
    prepTimeMinutes: 25,
    equipment: ['pressure-cooker'],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'dinner',
    ingredients: ['Moong dal 80g', 'Rice 80g', 'Ghee 1 tsp', 'Cumin', 'Turmeric', 'Vegetables 50g'],
    instructions: ['Wash rice and dal together', 'Pressure cook with vegetables and spices', 'Add ghee tadka', 'Serve hot with curd'],
  },
  {
    id: 'egg-curry',
    name: 'Egg Curry with Chapati',
    cuisine: 'indian',
    isVegetarian: true,
    isVegan: false,
    allergens: ['eggs'],
    tags: ['high-protein', 'egg'],
    macrosPer100g: { kcal: 160, protein: 11, carbs: 14, fat: 7, fiber: 2 },
    defaultPortionG: 300,
    prepTimeMinutes: 30,
    equipment: ['stove'],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'dinner',
    ingredients: ['Eggs 3', 'Chapati 2', 'Onion', 'Tomato', 'Ginger-garlic', 'Spices'],
    instructions: ['Hard boil eggs', 'Prepare onion-tomato masala', 'Add eggs to gravy', 'Simmer and serve with chapati'],
  },

  // SNACK OPTIONS
  {
    id: 'fruit-nuts',
    name: 'Mixed Fruits with Nuts',
    cuisine: 'any',
    isVegetarian: true,
    isVegan: true,
    allergens: ['nuts'],
    tags: ['quick', 'healthy-fats'],
    macrosPer100g: { kcal: 180, protein: 4, carbs: 25, fat: 8, fiber: 4 },
    defaultPortionG: 150,
    prepTimeMinutes: 5,
    equipment: [],
    costTier: 'medium',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'snack',
    ingredients: ['Mixed fruits 100g', 'Almonds 15g', 'Walnuts 10g'],
    instructions: ['Chop fruits', 'Add nuts', 'Serve fresh'],
  },
  {
    id: 'sprouts-chaat',
    name: 'Sprouts Chaat',
    cuisine: 'indian',
    isVegetarian: true,
    isVegan: true,
    allergens: [],
    tags: ['high-protein', 'high-fiber'],
    macrosPer100g: { kcal: 100, protein: 7, carbs: 15, fat: 2, fiber: 5 },
    defaultPortionG: 150,
    prepTimeMinutes: 10,
    equipment: [],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'snack',
    ingredients: ['Mixed sprouts 100g', 'Onion', 'Tomato', 'Lemon juice', 'Chaat masala', 'Coriander'],
    instructions: ['Steam sprouts lightly', 'Mix with chopped vegetables', 'Add lemon and spices', 'Serve fresh'],
  },
  {
    id: 'greek-yogurt',
    name: 'Greek Yogurt with Berries',
    cuisine: 'international',
    isVegetarian: true,
    isVegan: false,
    allergens: ['dairy'],
    tags: ['high-protein', 'probiotic'],
    macrosPer100g: { kcal: 90, protein: 10, carbs: 8, fat: 2, fiber: 1 },
    defaultPortionG: 200,
    prepTimeMinutes: 5,
    equipment: [],
    costTier: 'medium',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'snack',
    ingredients: ['Greek yogurt 150g', 'Mixed berries 50g', 'Honey 1 tsp (optional)'],
    instructions: ['Put yogurt in bowl', 'Top with berries', 'Drizzle honey if desired'],
  },
  {
    id: 'roasted-chana',
    name: 'Roasted Chana (Chickpeas)',
    cuisine: 'indian',
    isVegetarian: true,
    isVegan: true,
    allergens: [],
    tags: ['high-protein', 'high-fiber', 'crunchy'],
    macrosPer100g: { kcal: 160, protein: 8, carbs: 24, fat: 3, fiber: 6 },
    defaultPortionG: 50,
    prepTimeMinutes: 5,
    equipment: [],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'snack',
    ingredients: ['Roasted chana 50g', 'Chaat masala'],
    instructions: ['Add spices if desired', 'Enjoy as is'],
  },
  {
    id: 'vegetable-sticks',
    name: 'Veggie Sticks with Hummus',
    cuisine: 'mediterranean',
    isVegetarian: true,
    isVegan: true,
    allergens: ['sesame'],
    tags: ['low-calorie', 'high-fiber'],
    macrosPer100g: { kcal: 80, protein: 4, carbs: 10, fat: 3, fiber: 4 },
    defaultPortionG: 200,
    prepTimeMinutes: 10,
    equipment: [],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'snack',
    ingredients: ['Carrots', 'Cucumber', 'Bell peppers', 'Hummus 50g'],
    instructions: ['Cut vegetables into sticks', 'Serve with hummus for dipping'],
  },
  {
    id: 'makhana',
    name: 'Roasted Makhana (Fox Nuts)',
    cuisine: 'indian',
    isVegetarian: true,
    isVegan: true,
    allergens: [],
    tags: ['low-calorie', 'light'],
    macrosPer100g: { kcal: 110, protein: 4, carbs: 20, fat: 1, fiber: 2 },
    defaultPortionG: 30,
    prepTimeMinutes: 10,
    equipment: ['stove'],
    costTier: 'low',
    conditionFlags: { diabetes_ok: true, thyroid_ok: true, bp_ok: true },
    mealType: 'snack',
    ingredients: ['Makhana 30g', 'Ghee 1/2 tsp', 'Salt', 'Black pepper'],
    instructions: ['Dry roast makhana until crispy', 'Add ghee and spices', 'Cool and serve'],
  },
];
