INSERT INTO self_care_procedures (category_id, title, steps, description, benefits, ingredients, duration, frequency, precautions, image_url) VALUES
('e79bcfb8-a033-49c3-a7be-add91bc3df6f', 'Hydrating Aloe Vera Glow Mask', ARRAY['Cleanse face', 'Apply aloe gel mix', 'Leave for 15 mins', 'Rinse'], 'A hydrating mask that soothes irritated skin and restores moisture. Aloe Vera deeply nourishes and cools the skin.', ARRAY['Hydration', 'Skin calming', 'Reduces redness'], ARRAY['Aloe Vera', 'Honey', 'Cucumber'], '15 minutes', 'Daily', ARRAY['Patch-test aloe', 'Avoid eye area', 'Use fresh gel'], 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769683663/SKIN%20CARE/Hydrating_Aloe_Vera_Glow_Mask_blr0li.png'),

('e79bcfb8-a033-49c3-a7be-add91bc3df6f', 'Turmeric Brightening Face Pack', ARRAY['Mix ingredients', 'Apply evenly', 'Let dry', 'Wash gently'], 'Turmeric boosts radiance and reduces dark spots naturally. Yogurt adds mild exfoliation and moisture.', ARRAY['Brightening', 'Anti-inflammatory', 'Improves skin tone'], ARRAY['Turmeric', 'Yogurt', 'Honey'], '20 minutes', 'Weekly twice', ARRAY['Use very little turmeric', 'Avoid stains', 'Patch test for sensitivity'], 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769683664/SKIN%20CARE/Turmeric_Brightening_Face_Pack_sfdqe9.png'),

('e79bcfb8-a033-49c3-a7be-add91bc3df6f', 'Coffee Exfoliating Scrub', ARRAY['Mix scrub', 'Apply in circular motions', 'Rinse thoroughly'], 'Coffee powder gently exfoliates dead skin and improves circulation for a glowing look.', ARRAY['Exfoliation', 'Smooth skin', 'Increases blood flow'], ARRAY['Coffee powder', 'Coconut Oil', 'Sugar'], '10 minutes', 'Weekly once', ARRAY['Scrub gently', 'Avoid active acne', 'Do not over-exfoliate'], 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769683664/SKIN%20CARE/Coffee_Exfoliating_Scrub_kwr2b2.png'),

('e79bcfb8-a033-49c3-a7be-add91bc3df6f', 'Green Tea Antioxidant Toner', ARRAY['Brew tea', 'Cool it', 'Apply with cotton', 'Let absorb'], 'Green Tea fights free radicals and reduces excess oil while refreshing the skin.', ARRAY['Oil control', 'Refreshing', 'Anti-aging'], ARRAY['Green Tea', 'Rose water'], '5 minutes', 'Daily', ARRAY['Use cooled tea only', 'Store max 2 days', 'Avoid eye contact'], 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769683664/SKIN%20CARE/Green_Tea_Antioxidant_Toner_ffewi7.png'),

('e79bcfb8-a033-49c3-a7be-add91bc3df6f', 'Rice Water Skin Tightening Treatment', ARRAY['Soak rice', 'Collect rice water', 'Apply', 'Let dry', 'Rinse'], 'Rice water firms the skin and improves elasticity while brightening overall complexion.', ARRAY['Skin tightening', 'Brightening', 'Reduces pores'], ARRAY['Rice Water', 'Vitamin E'], '15 minutes', 'Weekly twice', ARRAY['Do not ferment too long', 'Rinse properly', 'Patch test'], 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769683665/SKIN%20CARE/Rice_Water_Skin_Tightening_Treatment_ldhmon.png'),

('e79bcfb8-a033-49c3-a7be-add91bc3df6f', 'Cucumber Cooling Eye Pack', ARRAY['Slice cucumber', 'Place on eyes', 'Rest'], 'Cucumber cools tired eyes, reduces puffiness, and hydrates delicate skin around the eyes.', ARRAY['Reduces puffiness', 'Cooling', 'Hydrating'], ARRAY['Cucumber'], '10 minutes', 'Daily', ARRAY['Use fresh slices', 'Do not press too hard', 'Avoid broken skin'], 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769683665/SKIN%20CARE/Cucumber_Cooling_Eye_Pack_kbznle.png'),

('e79bcfb8-a033-49c3-a7be-add91bc3df6f', 'Avocado Oil Deep Moisturizing Therapy', ARRAY['Warm oil slightly', 'Massage on face', 'Leave on', 'Wash or wipe off'], 'Avocado oil penetrates deeply to nourish very dry skin and restores softness.', ARRAY['Deep hydration', 'Softens skin', 'Repairs dryness'], ARRAY['Avocado Oil', 'Olive Oil'], '20 minutes', 'Weekly once', ARRAY['Avoid oily/acne-prone areas', 'Do not overuse oil', 'Patch test'], 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769683665/SKIN%20CARE/Avocado_Oil_Deep_Moisturizing_Therapy_wmqmwy.png'),

('e79bcfb8-a033-49c3-a7be-add91bc3df6f', 'Honey Anti-Bacterial Healing Mask', ARRAY['Clean face', 'Apply thin layer of honey', 'Let sit', 'Rinse'], 'Honey has anti-bacterial properties that help heal and soothe skin while adding natural glow.', ARRAY['Anti-bacterial', 'Glow boosting', 'Hydrating'], ARRAY['Honey', 'Lemon drops (optional)'], '15 minutes', 'Weekly twice', ARRAY['Do not use lemon daily', 'Avoid sunlight after lemon', 'Patch test for honey'], 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769683664/SKIN%20CARE/Honey_Anti-Bacterial_Healing_Mask_sl12uy.png'),

('e79bcfb8-a033-49c3-a7be-add91bc3df6f', 'Potato Tan-Removal Pack', ARRAY['Grate potato', 'Extract juice', 'Apply with cotton', 'Rinse after dry'], 'Potato juice naturally brightens skin and helps reduce suntan and pigmentation.', ARRAY['Tan removal', 'Brightening', 'Lightens dark spots'], ARRAY['Potato Juice', 'Rice Flour'], '20 minutes', 'Weekly once', ARRAY['Potato may cause dryness', 'Patch test', 'Avoid sensitive areas'], 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769683664/SKIN%20CARE/Potato_Tan-Removal_Pack_xf6ghb.png'),

('e79bcfb8-a033-49c3-a7be-add91bc3df6f', 'Olive Oil Night Skin Rejuvenation', ARRAY['Clean face', 'Apply few drops of olive oil', 'Massage gently'], 'Olive oil promotes skin repair overnight and reduces dryness, leaving the skin soft.', ARRAY['Overnight nourishment', 'Softness', 'Skin repair'], ARRAY['Olive Oil', 'Aloe Vera'], 'Leave overnight', 'Weekly twice', ARRAY['Avoid for oily or acne-prone skin', 'Use small quantity', 'Change pillow cover often'], 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769683663/SKIN%20CARE/Olive_Oil_Night_Skin_Rejuvenation_cerefb.png');