-- Insert North Indian Meals (51-80)
INSERT INTO public.meal_suggestions (goal, diet_type, meal_time, meal_name, items, calories_min, calories_max, protein_grams, region) VALUES
('weight_loss', 'veg', 'breakfast', 'Vegetable Poha', ARRAY['Vegetable poha', 'Peanuts (1 tbsp)'], 420, 420, 12, 'north_indian'),
('general_health', 'veg', 'breakfast', 'Stuffed Vegetable Paratha', ARRAY['Stuffed vegetable paratha (1)', 'Curd (1/2 cup)'], 480, 480, 14, 'north_indian'),
('muscle_gain', 'non_veg', 'breakfast', 'Egg Bhurji with Toasts', ARRAY['Egg bhurji (3 eggs)', '2 wheat toasts'], 620, 620, 35, 'north_indian'),
('weight_loss', 'veg', 'lunch', 'Multigrain Rotis with Dal Tadka', ARRAY['2 multigrain rotis', 'Dal tadka', 'Salad'], 480, 480, 20, 'north_indian'),
('general_health', 'veg', 'lunch', 'Rajma with Rice', ARRAY['Rajma (1 bowl)', 'Rice (3/4 cup)'], 520, 520, 22, 'north_indian'),
('muscle_gain', 'non_veg', 'lunch', 'Rotis with Chicken Curry', ARRAY['2 rotis', 'Chicken curry (150g)'], 650, 650, 40, 'north_indian'),
('weight_loss', 'non_veg', 'lunch', 'Grilled Chicken Salad', ARRAY['Grilled chicken salad'], 450, 450, 35, 'north_indian'),
('general_health', 'veg', 'dinner', 'Vegetable Soup with Paneer Bhurji', ARRAY['Vegetable soup', 'Paneer bhurji (75g)'], 420, 420, 20, 'north_indian'),
('muscle_gain', 'veg', 'dinner', 'Paneer Butter Masala Light', ARRAY['Paneer butter masala (light)', '2 rotis'], 650, 650, 30, 'north_indian'),
('weight_loss', 'veg', 'dinner', 'Vegetable Stir-fry with Curd', ARRAY['Vegetable stir-fry', 'Curd'], 380, 380, 14, 'north_indian'),
('weight_loss', 'veg', 'breakfast', 'Oats Porridge with Seeds', ARRAY['Oats porridge (milk)', 'Seeds topping'], 400, 400, 16, 'north_indian'),
('muscle_gain', 'non_veg', 'breakfast', 'Chicken Sandwich', ARRAY['Chicken sandwich (whole wheat)'], 580, 580, 32, 'north_indian'),
('general_health', 'veg', 'lunch', 'Rotis with Bhindi Sabzi', ARRAY['2 rotis', 'Bhindi sabzi', 'Dal'], 520, 520, 18, 'north_indian'),
('weight_loss', 'non_veg', 'dinner', 'Egg Curry with Roti', ARRAY['Egg curry (2 eggs)', '1 roti'], 420, 420, 26, 'north_indian'),
('muscle_gain', 'non_veg', 'dinner', 'Mutton Curry with Rotis', ARRAY['Mutton curry (120g)', '2 rotis'], 700, 700, 38, 'north_indian'),
('general_health', 'veg', 'breakfast', 'Besan Chilla', ARRAY['Besan chilla (2)', 'Mint chutney'], 450, 450, 18, 'north_indian'),
('weight_loss', 'veg', 'lunch', 'Chole with Roti', ARRAY['Chole (small bowl)', '1 roti', 'Salad'], 480, 480, 18, 'north_indian'),
('muscle_gain', 'veg', 'lunch', 'Veg Biryani with Paneer Raita', ARRAY['Veg biryani', 'Paneer raita'], 650, 650, 24, 'north_indian'),
('weight_loss', 'veg', 'dinner', 'Tomato Soup with Grilled Paneer', ARRAY['Tomato soup', 'Grilled paneer (75g)'], 390, 390, 20, 'north_indian'),
('general_health', 'non_veg', 'lunch', 'Rice with Fish Curry', ARRAY['Rice (1 cup)', 'Fish curry'], 520, 520, 30, 'north_indian'),
('weight_loss', 'veg', 'breakfast', 'Fruit Curd Bowl', ARRAY['Fruit + curd bowl', 'Seeds'], 350, 350, 14, 'north_indian'),
('muscle_gain', 'non_veg', 'lunch', 'Chicken Wrap', ARRAY['Chicken wrap (whole wheat)'], 600, 600, 35, 'north_indian'),
('general_health', 'veg', 'dinner', 'Rotis with Mixed Veg Curry', ARRAY['2 rotis', 'Mixed veg curry', 'Curd'], 500, 500, 16, 'north_indian'),
('weight_loss', 'non_veg', 'dinner', 'Tandoori Chicken with Salad', ARRAY['Tandoori chicken (150g)', 'Salad'], 420, 420, 38, 'north_indian'),
('muscle_gain', 'veg', 'breakfast', 'Paneer Paratha', ARRAY['Paneer paratha (1 large)', 'Curd'], 600, 600, 28, 'north_indian'),
('weight_loss', 'veg', 'lunch', 'Vegetable Pulao with Raita', ARRAY['Vegetable pulao (small)', 'Raita'], 480, 480, 14, 'north_indian'),
('muscle_gain', 'non_veg', 'dinner', 'Egg Fried Rice', ARRAY['Egg fried rice (2 eggs, less oil)'], 620, 620, 30, 'north_indian'),
('general_health', 'veg', 'breakfast', 'Dalia Upma', ARRAY['Dalia upma', 'Buttermilk'], 430, 430, 16, 'north_indian'),
('weight_loss', 'veg', 'dinner', 'Vegetable Khichdi with Curd', ARRAY['Vegetable khichdi', 'Curd'], 420, 420, 18, 'north_indian'),
('muscle_gain', 'non_veg', 'lunch', 'Butter Chicken Light', ARRAY['Butter chicken (light)', '2 rotis'], 700, 700, 38, 'north_indian'),

-- Insert South Indian Meals (81-105)
('weight_loss', 'veg', 'breakfast', 'Idlis with Sambar', ARRAY['2 idlis', '1 bowl sambar', 'Coconut chutney (1 tbsp)'], 380, 420, 15, 'south_indian'),
('weight_loss', 'veg', 'breakfast', 'Ragi Dosa with Sambar', ARRAY['Ragi dosa (2 small)', 'Vegetable sambar'], 400, 400, 16, 'south_indian'),
('weight_loss', 'non_veg', 'breakfast', 'Egg White Omelette with Millet Dosa', ARRAY['Egg white omelette (3 whites + 1 yolk)', '1 millet dosa'], 420, 420, 26, 'south_indian'),
('general_health', 'veg', 'breakfast', 'Vegetable Upma with Buttermilk', ARRAY['Vegetable upma (1 medium bowl)', 'Buttermilk (1 cup)'], 450, 450, 14, 'south_indian'),
('muscle_gain', 'non_veg', 'breakfast', 'Egg Omelette with Wheat Toasts', ARRAY['3 egg omelette', '2 whole-wheat toasts'], 600, 600, 32, 'south_indian'),
('weight_loss', 'veg', 'lunch', 'Brown Rice with Sambar', ARRAY['Brown rice (3/4 cup)', 'Sambar', 'Beans poriyal', 'Curd (1/2 cup)'], 480, 480, 18, 'south_indian'),
('general_health', 'veg', 'lunch', 'Phulkas with Vegetable Kurma', ARRAY['2 phulkas', 'Vegetable kurma', 'Curd'], 520, 520, 16, 'south_indian'),
('muscle_gain', 'non_veg', 'lunch', 'Rice with Chicken Curry', ARRAY['1 cup rice', 'Chicken curry (150g)', 'Vegetable stir-fry'], 680, 680, 38, 'south_indian'),
('weight_loss', 'non_veg', 'lunch', 'Lemon Rice with Grilled Fish', ARRAY['Lemon rice (small portion)', 'Grilled fish (120g)', 'Salad'], 500, 500, 30, 'south_indian'),
('general_health', 'veg', 'lunch', 'Curd Rice with Poriyal', ARRAY['Curd rice (1 cup)', 'Carrot beans poriyal'], 480, 480, 14, 'south_indian'),
('weight_loss', 'veg', 'dinner', 'Vegetable Soup with Paneer', ARRAY['Vegetable soup', 'Paneer cubes (75g)'], 400, 400, 20, 'south_indian'),
('muscle_gain', 'non_veg', 'dinner', 'Millet Rotis with Fish Curry', ARRAY['Millet rotis (2)', 'Fish curry (150g)'], 620, 620, 36, 'south_indian'),
('general_health', 'veg', 'dinner', 'Vegetable Pongal with Sambar', ARRAY['Vegetable pongal (1 bowl)', 'Sambar'], 450, 450, 15, 'south_indian'),
('weight_loss', 'veg', 'breakfast', 'Pesarattu with Ginger Chutney', ARRAY['Pesarattu (1 large)', 'Ginger chutney'], 420, 420, 18, 'south_indian'),
('muscle_gain', 'veg', 'breakfast', 'Moong Dal Chilla with Curd', ARRAY['Moong dal chilla (2)', 'Curd dip'], 550, 550, 28, 'south_indian'),
('weight_loss', 'non_veg', 'dinner', 'Chicken Soup with Wheat Toast', ARRAY['Chicken soup (large bowl)', '1 wheat toast'], 380, 380, 28, 'south_indian'),
('general_health', 'veg', 'breakfast', 'Idiyappam with Vegetable Kurma', ARRAY['Idiyappam (2)', 'Vegetable kurma'], 460, 460, 12, 'south_indian'),
('muscle_gain', 'non_veg', 'lunch', 'Egg Curry with Phulkas', ARRAY['Egg curry (3 eggs)', '2 phulkas'], 650, 650, 36, 'south_indian'),
('weight_loss', 'veg', 'lunch', 'Vegetable Khichdi with Curd', ARRAY['Vegetable khichdi (less rice)', 'Curd'], 430, 430, 18, 'south_indian'),
('general_health', 'non_veg', 'lunch', 'Rice with Fish Curry', ARRAY['Rice (1 cup)', 'Fish curry', 'Vegetables'], 540, 540, 28, 'south_indian'),
('weight_loss', 'veg', 'breakfast', 'Sprouts Sundal', ARRAY['Sprouts sundal (1 bowl)', 'Fruit (1 small)'], 360, 360, 20, 'south_indian'),
('muscle_gain', 'veg', 'lunch', 'Veg Pulao with Paneer Curry', ARRAY['Veg pulao (1 cup)', 'Paneer curry (100g)'], 650, 650, 26, 'south_indian'),
('general_health', 'veg', 'dinner', 'Vegetable Dosa with Sambar', ARRAY['Vegetable dosa (1 large)', 'Sambar'], 420, 420, 14, 'south_indian'),
('weight_loss', 'non_veg', 'lunch', 'Brown Rice with Grilled Chicken', ARRAY['Brown rice (3/4 cup)', 'Grilled chicken (120g)'], 480, 480, 34, 'south_indian'),
('muscle_gain', 'non_veg', 'dinner', 'Chicken Biryani with Raita', ARRAY['Chicken biryani (home-style)', 'Raita'], 700, 700, 40, 'south_indian');