
INSERT INTO food_products (name, category_id, purpose, description, advantages, medicinal_benefits, image_url)
VALUES 
  ('Walnut', '43651fe4-7a97-4b16-ad0d-cd07fd7437e6', 'Supports heart and brain health, provides plant omega‑3 fats, and helps keep you full between meals. Often eaten as snacks, in desserts, and sprinkled on salads or breakfast bowls.', 'Crunchy brain‑shaped nuts with a rich, slightly bitter taste, great for snacking and baking.', ARRAY['Heart health', 'Brain support', 'Omega‑3 fats', 'Plant protein', 'Satiety'], 'Traditionally used in some cultures to support heart and brain function and overall vitality. Not a substitute for medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524521/DRY FRUITS/Walnut_zhxxfm.png'),
  
  ('Dry Raisin', '43651fe4-7a97-4b16-ad0d-cd07fd7437e6', 'Provides quick natural energy, supports digestion with fiber, and adds iron and antioxidants to the diet. Commonly used in snacks, baked goods, cereals, and traditional sweets.', 'Naturally sweet dried grapes with a chewy texture, perfect for snacking or adding to dishes.', ARRAY['Natural energy', 'Digestive support', 'Source of iron', 'Antioxidants', 'Kid‑friendly snack'], 'Used in traditional remedies to support digestion, energy, and blood health. Not a replacement for medical care.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524520/DRY FRUITS/Raisin_Dry_wurbqg.png'),
  
  ('Pistachio (Pista)', '43651fe4-7a97-4b16-ad0d-cd07fd7437e6', 'Supports heart health, provides protein and fiber for fullness, and offers good fats and antioxidants. Enjoyed as a snack, in desserts, or as a topping for salads and sweets.', 'Small green nuts with a mild, slightly sweet flavour and satisfying crunch, often eaten roasted.', ARRAY['Heart health', 'Protein & fiber', 'Good fats', 'Antioxidants', 'Weight‑friendly snack'], 'Traditionally consumed to support heart health and overall strength. Not intended to treat or cure diseases.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524520/DRY FRUITS/Pista_oic6tf.png'),
  
  ('Job''s Tears (Coix Seeds)', '43651fe4-7a97-4b16-ad0d-cd07fd7437e6', 'Provides complex carbohydrates and some protein, supports steady energy, and adds fiber to the diet. Commonly used in warm porridge, soups, or herbal beverages.', 'Pearl‑like grains with a mild, nutty flavour, used in porridges, soups, and traditional drinks.', ARRAY['Steady energy', 'Fiber source', 'Mild and easy to digest', 'Versatile in cooking'], 'Used in some traditional systems to support digestive and joint health. Claims are traditional and not medically verified.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524519/DRY FRUITS/Jobs-tears_dtl8bq.png'),
  
  ('Date Fruit', '43651fe4-7a97-4b16-ad0d-cd07fd7437e6', 'Gives quick natural energy, supports digestion with fiber, and provides potassium and other minerals. Commonly used in snacks, smoothies, desserts, and as a natural sweetener.', 'Soft, naturally very sweet fruits with a caramel‑like taste, often eaten dried.', ARRAY['Natural sweetness', 'Quick energy', 'Digestive support', 'Source of minerals', 'Refined sugar alternative'], 'Traditionally used to support energy, digestion, and recovery after illness or fasting. Not a substitute for professional medical advice.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524518/DRY FRUITS/Date-fruit_pzxvrv.png'),
  
  ('Dried Blackberry', '43651fe4-7a97-4b16-ad0d-cd07fd7437e6', 'Rich in antioxidants and vitamin C, supports immunity and skin health, and adds fiber. Used in snacks, cereals, baking, and toppings for yogurt or desserts.', 'Dark purple dried berries with a sweet‑tart taste and chewy texture.', ARRAY['Antioxidant rich', 'Immune support', 'Skin health', 'Fiber source', 'Sweet‑tart flavour'], 'Traditionally valued for supporting immune and digestive health. Not intended to diagnose or treat any disease.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524517/DRY FRUITS/Blackberry_fruits_rwdfeb.png'),
  
  ('Cashew Nut', '43651fe4-7a97-4b16-ad0d-cd07fd7437e6', 'Provides healthy fats, plant protein, and minerals like magnesium and zinc. Commonly used in snacks, curries, gravies, desserts, and nut butters.', 'Creamy, mildly sweet nuts with a soft crunch, often eaten roasted or used in cooking.', ARRAY['Healthy fats', 'Plant protein', 'Mineral rich', 'Energy boost', 'Versatile in cooking'], 'Traditionally used to support strength, nerve health, and overall nourishment. Not a medical product.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524517/DRY FRUITS/Cashew-nut_r5y0jr.png');
