
INSERT INTO food_products (name, category_id, purpose, description, advantages, medicinal_benefits, image_url)
VALUES 
  ('Amla (Indian Gooseberry)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Supports immunity, skin health and digestion; commonly used in pickles, chutneys and traditional health tonics.', 'Small green fruit with a very sour taste, used fresh, pickled, or in powders and juices.', ARRAY['Immunity', 'Vitamin C rich', 'Antioxidants', 'Hair & skin support', 'Digestive health'], 'Widely used in traditional medicine to support immunity, digestion, hair growth and overall vitality. Not a substitute for medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524450/VEGETABLES/Amla_eahnuk.png'),
  
  ('Beetroot', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Supports heart health, blood health and stamina; used in salads, juices, curries and snacks.', 'Deep red root vegetable with a sweet, earthy taste, eaten raw, juiced, roasted or boiled.', ARRAY['Heart health', 'Blood support', 'Natural energy', 'Fiber', 'Antioxidants'], 'Traditionally used to support blood health, stamina and liver cleansing. Not intended to replace professional medical advice.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524451/VEGETABLES/Beetroots_mvzfbe.png'),
  
  ('Bitter Gourd (Bitter Melon)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Often used to help support blood sugar control and digestion; commonly stuffed, fried or cooked with spices.', 'Green, bumpy vegetable with a strong bitter taste, commonly cooked in stir‑fries and curries.', ARRAY['Blood sugar support', 'Digestive aid', 'Low calorie', 'Fiber', 'Traditional remedy'], 'Used in traditional systems to help manage blood sugar and purify the blood. Not a medicine for diabetes—consult a doctor.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524452/VEGETABLES/bitter-gourd_irntxe.png'),
  
  ('Bottle Gourd', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Hydrates the body, light on the stomach and supports digestion; used in curries, gravies and juices.', 'Light green, soft vegetable with high water content and mild flavour, easy to digest.', ARRAY['Hydrating', 'Easy to digest', 'Low calorie', 'Good for summer', 'Gentle on stomach'], 'Traditionally used as a cooling food to support digestion and manage acidity. Not a replacement for medical care.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524451/VEGETABLES/bottle_gourd_hbbkt9.png'),
  
  ('Cabbage', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides fiber and vitamins, supports gut health and low‑calorie meals; used in stir‑fries, salads and curries.', 'Leafy, compact vegetable with crisp layers, eaten raw in salads or cooked in many dishes.', ARRAY['Fiber', 'Low calorie', 'Gut health', 'Vitamin C', 'Versatile'], 'Traditionally used to support digestion and as a light vegetable for weight‑friendly diets. Not a medical product.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524452/VEGETABLES/Cabbage_fyhv6t.png'),
  
  ('Capsicum (Bell Pepper)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Adds vitamin C, colour and crunch to meals; used in salads, stir‑fries, pizza toppings and gravies.', 'Bright coloured, crisp peppers with a mildly sweet flavour, eaten raw or cooked.', ARRAY['Vitamin C', 'Antioxidants', 'Low calorie', 'Adds colour', 'Crunchy texture'], 'Traditionally used to support immunity and provide antioxidant protection. Not a substitute for medicines.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524452/VEGETABLES/capsicum-bell_pepper_fuuylv.png'),
  
  ('Carrot', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Supports eye health, skin and immunity with beta‑carotene; used in salads, juices, curries and sweets.', 'Crunchy orange root with a naturally sweet taste, enjoyed raw or cooked.', ARRAY['Eye health', 'Beta‑carotene', 'Fiber', 'Kid‑friendly', 'Versatile'], 'Traditionally valued for supporting vision and immunity. Not intended as a cure for eye conditions.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524453/VEGETABLES/Carrots_euh7u0.png'),
  
  ('Cauliflower', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Low in calories yet filling, supports weight management and fiber intake.', 'White, compact florets with a mild taste, used in curries, stir‑fries and rice alternatives.', ARRAY['Low carb', 'Fiber', 'Weight‑friendly', 'Versatile substitute', 'Mild flavour'], 'Often included in light diets to support weight control and digestion. Not a medicinal treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524454/VEGETABLES/cauliflower_grplzi.png'),
  
  ('Cluster Beans (Guar)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides fiber and plant nutrients, supports digestion and simple home‑style meals.', 'Slim green beans with a slightly bitter taste, cooked in dry curries and stir‑fries.', ARRAY['Fiber', 'Traditional vegetable', 'Digestive support', 'Low calorie'], 'Used traditionally to support digestion and as part of diabetic‑friendly diets. Not a substitute for medication.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524455/VEGETABLES/cluster_beans_h1wmwb.png'),
  
  ('Coconut', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Adds healthy fats, energy and flavour to curries, chutneys and desserts.', 'White, fleshy kernel with a rich, mildly sweet taste; used fresh, dried and as oil or milk.', ARRAY['Healthy fats', 'Energy', 'Flavor enhancer', 'Versatile use', 'Traditional cooking'], 'Traditionally used for energy, skin and hair health. Not a replacement for professional care.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524456/VEGETABLES/Coconut_oziuie.png'),
  
  ('Cucumber', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Hydrates the body, low in calories and soothing for digestion; used in salads, raitas and detox waters.', 'Crunchy, watery vegetable with a refreshing taste, eaten mainly raw.', ARRAY['Hydration', 'Low calorie', 'Cooling', 'Light on stomach', 'Good for summer'], 'Used traditionally to cool the body and ease acidity. Not a medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524456/VEGETABLES/Cucumber_tqbz3u.png'),
  
  ('Drumstick (Moringa Pods)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Adds fiber, minerals and a unique flavour to dishes; supports digestion and traditional home cooking.', 'Long, slender pods with soft inner flesh, used in sambar, curries and soups.', ARRAY['Fiber', 'Mineral rich', 'Traditional food', 'Supports digestion'], 'Part of traditional diets believed to support joint and digestive health. Not a substitute for medical care.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524457/VEGETABLES/Drumstick_eot3zz.png'),
  
  ('Elephant Foot Yam', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides complex carbohydrates and fiber, making meals filling and satisfying.', 'Starchy tuber with a dense texture, cooked in curries, fries and gravies.', ARRAY['Energy', 'Fiber', 'Filling', 'Traditional root', 'Versatile in cooking'], 'Used in some traditional cuisines for digestive and metabolic support. Not a medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524458/VEGETABLES/Elephant-foot_yam_swpy7f.png'),
  
  ('Flat Beans', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides fiber and plant protein, supports everyday home‑style meals.', 'Broad, flat green beans with a mild taste, used in stir‑fries and dals.', ARRAY['Fiber', 'Plant protein', 'Light vegetable', 'Home cooking'], 'Traditionally included in light diets for digestion and nutrition. Not a substitute for treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524457/VEGETABLES/flat_beans_nelvdv.png'),
  
  ('Garlic', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Adds strong flavour and is traditionally believed to support heart and immune health.', 'Strong‑flavoured bulbs used as a seasoning in many savoury dishes.', ARRAY['Flavor booster', 'Heart support (traditional)', 'Immune support', 'Antioxidants'], 'Widely used in traditional remedies for heart health and immunity. Not a replacement for prescribed medicines.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524458/VEGETABLES/garlic_yvoosp.png'),
  
  ('Ginger', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Helps relieve nausea and indigestion, adds warmth and flavour to food and drinks.', 'Spicy, aromatic root used fresh or dried in curries, teas and medicines.', ARRAY['Digestive aid', 'Anti‑nausea', 'Warming spice', 'Immune support (traditional)'], 'Commonly used in traditional medicine for digestion, colds and nausea. Not a substitute for medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524458/VEGETABLES/ginger_bjusn6.png'),
  
  ('Green Peas', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides plant protein and fiber; used in curries, rice dishes, soups and snacks.', 'Small green seeds with a mildly sweet taste, eaten fresh or dried.', ARRAY['Plant protein', 'Fiber', 'Kid‑friendly', 'Versatile', 'Filling'], 'Included in balanced diets for protein and fiber. Not a medicinal product.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524459/VEGETABLES/green_peas_f5mwzq.png'),
  
  ('Green Ivy Gourd', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Light and easy to digest, commonly used in simple home‑style dishes.', 'Small green, elongated vegetable with a mild taste, used in stir‑fries and curries.', ARRAY['Light vegetable', 'Easy to digest', 'Everyday cooking', 'Low calorie'], 'Traditionally used in some regions to support blood sugar balance. Not a replacement for medical advice.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524459/VEGETABLES/greenIvy-gourd_fjngr3.png'),
  
  ('Ivy Gourd', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Supports light meals and routine vegetable intake in daily cooking.', 'Small gourd with tender flesh, used in many South Indian and Asian dishes.', ARRAY['Traditional vegetable', 'Light', 'Simple cooking', 'Fiber'], 'Used in folk medicine along with other foods for metabolic support. Not a drug.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524460/VEGETABLES/Ivy-gourd_ek0mvp.png'),
  
  ('Ladies'' Finger (Okra)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides fiber and is popular in many regional dishes; supports digestion.', 'Long green pods with a slightly sticky texture, used in fries, gravies and stir‑fries.', ARRAY['Fiber', 'Traditional favourite', 'Good with rice & rotis', 'Digestive support'], 'Traditionally considered useful for digestion and blood sugar support. Not a medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524461/VEGETABLES/Ladies-finger_w8w58a.png'),
  
  ('Onion', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Adds flavour, mild sweetness and some antioxidants to everyday cooking.', 'Pungent bulbs used as a base in most savoury dishes, eaten raw or cooked.', ARRAY['Flavor base', 'Antioxidants', 'Versatile', 'Used daily'], 'Traditionally used for immunity and respiratory support. Not a replacement for prescribed medicines.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524461/VEGETABLES/onions_iskhyu.png'),
  
  ('Plantain Flower (Banana Flower)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Rich in fiber and traditionally used in women''s health recipes and digestive dishes.', 'Purple flower of the banana plant, used in traditional curries and stir‑fries.', ARRAY['Fiber', 'Traditional food', 'Women''s health support (traditional)', 'Gut health'], 'Used in traditional recipes to support menstrual health and digestion. Not a medical product.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524463/VEGETABLES/plantain_flower_gvzmq5.png'),
  
  ('Plantain Stem', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'High in fiber and considered cleansing; used in light, traditional recipes.', 'Tender inner stem of the banana plant, used in poriyals, kootu and juices.', ARRAY['Fiber', 'Light', 'Traditional detox food', 'Digestive support'], 'Traditionally used for urinary and digestive support. Not meant as a cure or treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524464/VEGETABLES/plantain_stem_bhxfvj.png'),
  
  ('Potato', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides energy and satiety; used in curries, fries, snacks and gravies.', 'Starchy root with mild flavour, used in countless dishes worldwide.', ARRAY['Energy', 'Filling', 'Versatile', 'Comfort food'], 'Included in normal diets for energy; not considered a medicinal food.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524465/VEGETABLES/Potatos_gq4ony.png'),
  
  ('Pumpkin', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides beta‑carotene and fiber; supports eye health and gentle digestion.', 'Orange fleshy vegetable with natural sweetness, used in curries, sambar and sweets.', ARRAY['Beta‑carotene', 'Fiber', 'Gentle on stomach', 'Versatile'], 'Traditionally used in light, easily digestible meals. Not a medical food.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524466/VEGETABLES/Pumpkin_zhomvy.png'),
  
  ('Radish', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Supports digestion and appetite; used in salads, parathas and sambar.', 'Crisp root with a sharp, peppery taste, eaten raw or cooked.', ARRAY['Digestive support', 'Crunchy', 'Low calorie', 'Traditional use'], 'Traditionally used to support liver and digestive health. Not a substitute for medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524468/VEGETABLES/radish_lmjvcr.png'),
  
  ('Raw Mango', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Adds tangy flavour and vitamin C; popular in summer recipes.', 'Green unripe mango with sour taste, used in pickles, chutneys and curries.', ARRAY['Vitamin C', 'Tangy taste', 'Summer food', 'Appetite stimulant'], 'Traditionally used to cool the body and support digestion in summer. Not a medicine.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524468/VEGETABLES/raw_mangoes_il7fnp.png'),
  
  ('Raw Plantain (Green Banana)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides complex carbs and fiber, making dishes filling and satisfying.', 'Starchy, unripe banana used as a vegetable in curries, fries and gravies.', ARRAY['Energy', 'Fiber', 'Traditional vegetable', 'Filling'], 'Traditionally used in light diets and for digestive balance. Not a medical product.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524470/VEGETABLES/raw_plantain_koh78s.png'),
  
  ('Red Pumpkin', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides beta‑carotene, fiber and gentle sweetness in meals.', 'Bright orange‑red pumpkin with sweet taste, used in curries, sambar and sweets.', ARRAY['Beta‑carotene', 'Fiber', 'Gentle', 'Versatile', 'Kid‑friendly'], 'Included in easy‑to‑digest, nourishing recipes. Not for medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524470/VEGETABLES/red_pumpkins_j4pian.png'),
  
  ('Ridge Gourd', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Light, low‑calorie vegetable ideal for simple, daily cooking.', 'Long green gourd with ridges, soft and light after cooking.', ARRAY['Low calorie', 'Light', 'Easy to digest', 'Home‑style recipes'], 'Traditionally used in light meals to support digestion. Not a medical product.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524472/VEGETABLES/ridge_gourd_jia8ii.png'),
  
  ('Shallots (Pearl Onions)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Adds sweetness and flavour; used in many South Indian dishes.', 'Small, sweet onions used in sambar, pickles and curries.', ARRAY['Flavor', 'Mild sweetness', 'Traditional recipes', 'Antioxidants'], 'Used in folk remedies for immunity and digestive health. Not a replacement for medical care.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524472/VEGETABLES/shallot-spearl_onions_xztr1j.png'),
  
  ('Snake Gourd', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'A light, water‑rich vegetable used in simple, home‑style dishes.', 'Long, thin gourd with soft flesh, commonly cooked in curries and poriyals.', ARRAY['Hydration', 'Light', 'Easy to digest', 'Traditional'], 'Traditionally used in light diets and for cooling the body. Not a medical food.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524471/VEGETABLES/Snake-gourd_r4umwx.png'),
  
  ('Spine Gourd (Kantola)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Adds texture and variety to meals, with fiber and traditional benefits.', 'Small, spiky green gourd with firm flesh, used in fries and curries.', ARRAY['Fiber', 'Texture', 'Traditional vegetable', 'Seasonal'], 'Used in traditional cooking for digestive and seasonal support. Not a substitute for treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524472/VEGETABLES/spine-gourd_jicsxs.png'),
  
  ('Sponge Gourd', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Very light and easy to digest, suitable for simple curries and sabzis.', 'Soft, sponge‑like gourd with mild taste, cooks quickly.', ARRAY['Light', 'Easy to digest', 'Quick cooking', 'Low calorie'], 'Often used in light diets during illness recovery. Not a medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524472/VEGETABLES/sponge-gourd_tjgyee.png'),
  
  ('Sweet Corn', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides energy, fiber and sweetness; popular as snack and in salads, soups and pizzas.', 'Yellow kernels with a sweet taste, eaten boiled, roasted or in dishes.', ARRAY['Energy', 'Fiber', 'Kid‑friendly', 'Snackable'], 'Included in balanced diets for energy and fiber; not a medicinal food.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524472/VEGETABLES/Sweet_corn_cw4ycv.png'),
  
  ('Tapioca (Cassava Root)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides high energy and satiety; used in fasting and regional dishes.', 'Starchy root used boiled, in snacks and as tapioca pearls. Must be cooked properly.', ARRAY['Energy', 'Filling', 'Traditional fasting food', 'Gluten‑free carb'], 'Used in some cultures for energy‑dense diets. Not a medicinal product.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524473/VEGETABLES/Tapioca_divt9g.png'),
  
  ('Taro (Colocasia Root)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides energy and a unique flavour in regional recipes.', 'Starchy tuber with creamy texture after cooking, used in fries, curries and roasts.', ARRAY['Energy', 'Comfort food', 'Traditional root', 'Filling'], 'Used in local cuisines as part of nourishing meals. Not a medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524473/VEGETABLES/taro-colocasia_root_ylzwlh.png'),
  
  ('Tomato', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Adds tanginess, colour and lycopene (an antioxidant) to everyday dishes.', 'Juicy red fruit used as a base in sauces, curries, sambar and salads.', ARRAY['Antioxidants', 'Lycopene', 'Versatile', 'Everyday use'], 'Traditionally included for heart and skin supportive nutrients. Not a medicine.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524474/VEGETABLES/Tomato_lqxmgk.png'),
  
  ('Tomatoes (Mixed / Multiple)', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Same as tomato—base ingredient for many Indian and global recipes.', 'Fresh tomatoes in different sizes or forms used widely in cooking.', ARRAY['Antioxidants', 'Base for gravies', 'Versatile', 'Adds colour & tang'], 'Same traditional uses as tomato; not a replacement for medical treatment.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524476/VEGETABLES/Tomatos_m3xvwf.png'),
  
  ('Greater Yam', '69f11826-5d1d-4277-900e-35e2bfde14ad', 'Provides energy and fiber as a staple root vegetable.', 'Large starchy tuber used in curries, fries and festive dishes.', ARRAY['Energy', 'Fiber', 'Traditional root', 'Filling'], 'Used in traditional cuisines for strength and nourishment. Not a medical product.', 'https://res.cloudinary.com/di4yfgmlz/image/upload/v1760524477/VEGETABLES/yamgreater-yam_n72kbi.png');
