INSERT INTO self_care_procedures (title, steps, description, benefits, ingredients, duration, frequency, precautions, image_url, category_id)
VALUES
(
  'Morning Yoga Routine',
  ARRAY['Step 1 – Warm-up stretches: Stand straight, raise your arms overhead, and gently bend left and right for 30 seconds.', 'Step 2 – Sun Salutations: Move through forward bend, plank, cobra, and downward dog slowly for 5 rounds.', 'Step 3 – Breathing: Sit cross-legged and take slow deep breaths (inhale 4 sec, exhale 4 sec) for 2 minutes.'],
  'A relaxing morning sequence to wake up your muscles and calm the mind. Enhances flexibility and energy.',
  ARRAY['Flexibility improvement', 'Stress reduction', 'Better posture'],
  ARRAY['Yoga mat', 'Water bottle', 'Calm space'],
  '20 minutes',
  'Daily',
  ARRAY['Avoid over-stretching', 'Maintain slow breathing', 'Keep spine aligned'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695235/FITNESS%20CARE/Morning_Yoga_Routines_llfdgr.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'High-Intensity Interval Training (HIIT)',
  ARRAY['Step 1 – Warm-up: March in place or slow jog for 2 minutes to activate muscles.', 'Step 2 – Intense bursts: Do 30 seconds of fast moves (jumping jacks, high knees, or burpees), followed by 15 seconds rest. Repeat 5 cycles.', 'Step 3 – Cooldown: Walk slowly and stretch your legs and arms for 2 minutes.'],
  'A quick workout alternating high effort and rest for maximum calorie burn.',
  ARRAY['Fat loss', 'Improved endurance', 'Increased metabolism'],
  ARRAY['Timer', 'Workout clothes', 'Water'],
  '15 minutes',
  'Weekly 3 times',
  ARRAY['Avoid if injured', 'Do proper warm-up', 'Maintain form'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695237/FITNESS%20CARE/High-Intensity_Interval_Training_HIIT_jusspi.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Evening Meditation Practice',
  ARRAY['Step 1 – Sit comfortably: Sit on a cushion or chair with your back straight and shoulders relaxed.', 'Step 2 – Focus on breathing: Close your eyes and take slow deep breaths, feeling the air enter and leave.', 'Step 3 – Release thoughts: If thoughts appear, gently shift your focus back to breathing without force.'],
  'A mental relaxation routine that eases stress and prepares your mind for peaceful sleep.',
  ARRAY['Mental clarity', 'Better sleep', 'Reduced anxiety'],
  ARRAY['Quiet room', 'Meditation app', 'Cushion'],
  '10 minutes',
  'Daily',
  ARRAY['Avoid lying down', 'Keep spine straight', 'Maintain calm environment'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695241/FITNESS%20CARE/Evening_Meditation_Practice_xg1byt.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Strength Training Basics',
  ARRAY['Step 1 – Warm-up: Rotate shoulders, hips, and do light jogging for 2 minutes.', 'Step 2 – Weight exercises: Do 10 squats, 10 push-ups, and 10 dumbbell curls (or water-bottle curls). Repeat 2 rounds.', 'Step 3 – Stretch: Sit and stretch arms, legs, and back for 2 minutes.'],
  'A simple routine to build muscle strength using light weights or your own body weight.',
  ARRAY['Muscle growth', 'Better bone density', 'Increased stamina'],
  ARRAY['Dumbbells', 'Mat', 'Water'],
  '30 minutes',
  'Weekly 4 times',
  ARRAY['Start with light weight', 'Avoid jerky lifts', 'Maintain straight posture'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695234/FITNESS%20CARE/Strength_Training_Basics_nxpqx9.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Morning Walking Routine',
  ARRAY['Step 1 – Warm-up walk: Start with slow walking for 3 minutes to ease your body.', 'Step 2 – Brisk walking: Increase speed and walk at a fast pace without running for 20 minutes.', 'Step 3 – Cooldown: Slow down again and stretch calves and thighs.'],
  'A refreshing walk that promotes heart health and boosts energy early in the day.',
  ARRAY['Weight control', 'Improved circulation', 'Better mood'],
  ARRAY['Walking shoes', 'Water', 'Comfortable clothes'],
  '30 minutes',
  'Daily',
  ARRAY['Avoid uneven surfaces', 'Stay hydrated', 'Wear supportive shoes'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695233/FITNESS%20CARE/Morning_Walking_Routine_pe4kil.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Core Strengthening Circuit',
  ARRAY['Step 1 – Plank: Hold a plank position with straight back for 20–30 seconds.', 'Step 2 – Crunches: Lie on your back and lift your upper body gently for 15 reps.', 'Step 3 – Leg raises: Lift both legs up and down slowly without touching the floor for 12 reps.'],
  'A focused routine to strengthen stomach and lower back muscles for better body stability.',
  ARRAY['Strong core', 'Better balance', 'Reduced back pain'],
  ARRAY['Mat', 'Timer', 'Water'],
  '15 minutes',
  'Weekly 3 times',
  ARRAY['Avoid neck strain', 'Keep core tight', 'Move slowly'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695233/FITNESS%20CARE/Core_Strengthening_Circuit_oh4p6w.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Flexibility Stretch Routine',
  ARRAY['Step 1 – Hamstring stretch: Sit and reach your hands toward your toes, hold for 20 seconds.', 'Step 2 – Quadriceps stretch: Stand on one foot, pull the other heel toward your butt, hold for 20 seconds.', 'Step 3 – Shoulder stretch: Pull one arm across your chest using the other hand, hold for 20 seconds each side.'],
  'A gentle stretching sequence to improve flexibility and release muscle tightness.',
  ARRAY['Better mobility', 'Injury prevention', 'Relaxed muscles'],
  ARRAY['Mat', 'Comfortable clothes', 'Water'],
  '10 minutes',
  'Daily',
  ARRAY['Don''t force stretch', 'Breathe slowly', 'Keep movements smooth'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695233/FITNESS%20CARE/Flexibility_Stretch_Routine_mabmgw.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Cycling Fitness Plan',
  ARRAY['Step 1 – Warm-up ride: Cycle at slow speed for 3 minutes.', 'Step 2 – Moderate ride: Pedal at medium pace, keeping legs moving continuously for 20 minutes.', 'Step 3 – Cooldown: Slow cycling followed by leg stretches.'],
  'A cardio workout that boosts endurance and strengthens leg muscles.',
  ARRAY['Weight loss', 'Strong legs', 'Heart health'],
  ARRAY['Bicycle', 'Helmet', 'Water'],
  '30 minutes',
  'Weekly 3 times',
  ARRAY['Wear helmet', 'Avoid traffic', 'Don''t over-speed'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695248/FITNESS%20CARE/Cycling_Fitness_Plan_ukfiar.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Full-Body Stretch & Relax Routine',
  ARRAY['Step 1 – Neck roll: Slowly roll your neck clockwise and anticlockwise for 10 seconds each.', 'Step 2 – Spine twist: Sit cross-legged and twist your torso gently left and right.', 'Step 3 – Hip opener: Sit in butterfly pose and gently push knees toward the floor.'],
  'A body-relaxing routine that relieves stress and improves flexibility across all major joints.',
  ARRAY['Relaxation', 'Joint mobility', 'Stress relief'],
  ARRAY['Mat', 'Calm music', 'Water'],
  '15 minutes',
  'Daily',
  ARRAY['Move gently', 'Avoid fast motions', 'Keep breathing steady'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695232/FITNESS%20CARE/full_body_stretching_gapctt.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Home Cardio Workout',
  ARRAY['Step 1 – Jumping jacks: Stand straight and jump while spreading arms and legs for 30 seconds.', 'Step 2 – Spot jog: Jog in one place lifting your knees high for 45 seconds.', 'Step 3 – Arm swings: Swing both arms forward and backward for 30 seconds to boost circulation.'],
  'A simple home-friendly cardio routine that helps burn calories and improve stamina.',
  ARRAY['Increased stamina', 'Heart health', 'Calorie burn'],
  ARRAY['Mat', 'Water bottle', 'Space to move'],
  '20 minutes',
  'Weekly 4 times',
  ARRAY['Avoid slippery floors', 'Warm up properly', 'Don''t overexert'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695234/FITNESS%20CARE/Home_Cardio_Workout_bjizve.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Guided Meditation and Breathing Session',
  ARRAY['Sit comfortably', 'Close eyes and relax shoulders', 'Focus on slow deep inhales and exhales', 'Observe thoughts without judgment', 'End with a few normal breaths and open eyes'],
  'Meditation with deep breathing relaxes the nervous system and reduces stress. It improves mental clarity, emotional balance, and overall well-being.',
  ARRAY['Reduces stress', 'Improves focus', 'Supports emotional balance', 'Enhances sleep quality'],
  ARRAY['Quiet space', 'Comfortable chair or cushion', 'Optional soft music'],
  '10 minutes',
  'Daily',
  ARRAY['Sit with straight but relaxed spine', 'Do not force breathing', 'Stop if you feel dizzy', 'Avoid meditating when extremely sleepy'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695257/FITNESS%20CARE/Guided_Meditation_and_Breathing_Session_kdhb3h.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Low-Impact Home Cardio Routine',
  ARRAY['Warm up with step-touch movements', 'Do low-impact marching in place', 'Add side steps and gentle knee lifts', 'Include light arm swings', 'Cool down with slow walking and stretching'],
  'Low-impact cardio raises your heart rate without heavy jumping, making it joint-friendly. It supports heart health, endurance, and calorie burning.',
  ARRAY['Improves heart fitness', 'Burns calories safely', 'Builds endurance', 'Suitable for many ages'],
  ARRAY['Non-slip floor space', 'Comfortable shoes', 'Water bottle'],
  '20 minutes',
  'Weekly three to five times',
  ARRAY['Avoid sudden fast movements', 'Wear proper footwear', 'Keep movements pain-free', 'Stop if dizzy or extremely breathless'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695251/FITNESS%20CARE/Low-Impact_Home_Cardio_Routine_cfg5gp.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
),
(
  'Core Strength and Stability Routine',
  ARRAY['Warm up with gentle twists', 'Perform basic planks or modified planks', 'Do bird-dog exercise', 'Do lying leg raises or marches', 'Finish with gentle back and hip stretches'],
  'Core training strengthens the muscles around your abdomen and lower back. A strong core supports posture, balance, and reduces the risk of back problems.',
  ARRAY['Strengthens core muscles', 'Supports healthy posture', 'Improves balance', 'Reduces back strain risk'],
  ARRAY['Exercise mat', 'Comfortable clothing', 'Timer or stopwatch'],
  '15 minutes',
  'Weekly three times',
  ARRAY['Keep core engaged but do not hold breath', 'Avoid straining neck', 'Modify exercises if you have back pain', 'Stop if sharp pain appears'],
  'https://res.cloudinary.com/di4yfgmlz/image/upload/v1769695247/FITNESS%20CARE/Core_Strength_and_Stability_Routine_gur7zg.png',
  'c4c9225b-0255-42c5-86fc-cc924fbd2228'
);